### ISSUE TITLE
Maybe ContributorsCount animation should only be at the beginning of screen transition

### ISSUE THREAD

**Issue by kosenda** [DroidKaigi/conference-app-2024#1001]
## Overview
I think it is a bit overstated to have the animation move every time the ContributorsCountItem is shown or hidden when scrolling after the animation has moved.

https://github.com/user-attachments/assets/d08ca095-7f0f-4388-8ad0-83de041987fa

https://github.com/DroidKaigi/conference-app-2024/blob/86e8139fb1293655dfc9ebe6c3daf1c3fb475951/feature/contributors/src/commonMain/kotlin/io/github/droidkaigi/confsched/contributors/component/ContributorsCountItem.kt#L29-L70

**Comment by takahirom** [comment]
Thanks! Assgined!
