### ISSUE TITLE
In SearchScreen, keyboard should't be displayed when setting filters.

### ISSUE THREAD

**Issue by kosenda** [DroidKaigi/conference-app-2024#1011]
## Overview
In SearchScreen, if you set a filter when the keyboard is hidden, the keyboard will appear.
Personally, I think it would be preferable for users if the keyboard did not appear.

https://github.com/user-attachments/assets/17aabf96-ed79-4846-b43a-f6edb1d4361a

## Ref
- https://github.com/DroidKaigi/conference-app-2024/pull/1002

**Comment by kosenda** [comment]
Here it is, but I couldn't reproduce the video movement when I started it with the latest main branch 🙇
Maybe it was just a temporary problem on my device.

**Comment by takahirom** [comment]
Thanks. Maybe the update to the libraries did the trick. Let me close this issue.
