### ISSUE TITLE
If it's selected AboutScreen again when selecting AboutScreen, it can not transition to its other child screens.

### ISSUE THREAD

**Issue by nyafunta9858** [DroidKaigi/conference-app-2024#1016]
# Overview
If it's selected AboutScreen again when selecting AboutScreen, it can not transition to other child screens.

# Details

https://github.com/user-attachments/assets/f5e3cbe9-f8f1-42ea-9a9e-261bcef2be0c

**Comment by takahirom** [comment]
I can't reproduce the issue. Where did you check it?

**Comment by takahirom** [comment]
I'm using 
API Level 33 emulator 
debug build 
main([82bcd5c](https://github.com/DroidKaigi/conference-app-2024/commit/82bcd5c65a2d7bafed797eaed98c1cdbc99c3822))

**Comment by Corvus400** [comment]
@takahirom @nyafunta9858 
I was able to check it in my own environment.
There may be a problem if you use SharedTransitionLayout.
The problem does not occur on iOS devices that do not use SharedTransitionLayout in the main, but the same problem occurs on iOS devices that have introduced SharedTransitonaLayout.

iOS main OK | iOS shared transition layout NG | Android main NG
:--: | :--: | :--:
<video src="https://github.com/user-attachments/assets/365aa330-07c8-41c5-a36c-66772c7052bb" width="300" > | <video src="https://github.com/user-attachments/assets/7aca2609-385a-4381-999b-f73f4fa3d1ac" width="300" > | <video src="https://github.com/user-attachments/assets/1be7a6c3-0bad-4d54-98af-a0411626a219" width="300" >

**Comment by nyafunta9858** [comment]
I have checked with the Android 14  Pixel Fold physical device!

**Comment by takahirom** [comment]
When scrolling a little it works. I'm not sure at all.

**Comment by takahirom** [comment]
<img width="892" alt="image" src="https://github.com/user-attachments/assets/7ecca474-9d43-4852-8745-dedc50c72a1b">
I think we can remove the dropUnlessResumed.

**Comment by takahirom** [comment]
@Corvus400 @nyafunta9858 
I'm not sure if this is the same issue that I am experiencing. Could you try removing the dropUnlessResumed() and try again?

**Comment by Corvus400** [comment]
@takahirom @nyafunta9858 
At least on Android, it looks like the navigation problem has been solved, as shown in the video attached to the PR above.
