### ISSUE TITLE
StaffScreen and Contributors loading positions are very different and not consistent

### ISSUE THREAD

**Issue by kosenda** [DroidKaigi/conference-app-2024#1022]
## Overview
- StaffScreen and ContributorsScreen have similar UIs, but their loading positions are quite different
- Not a similar UI, but TimetableitemDetailScreen had the loading position in the middle

|StaffScreen|Contributors|
|---|---|
|<img src="https://github.com/user-attachments/assets/0f8f547a-e14a-49d1-9fd5-7a9b3d647d46" width="300">|<img src="https://github.com/user-attachments/assets/daf5f63d-912e-49ad-8dcc-b7c6b8ac38f1" width="300">|

## incidentally
SponsorsScreen
<img src="https://github.com/user-attachments/assets/b22403b5-69ff-44c2-9692-f604bb8733c8" width="300">

**Comment by GGBBB2000** [comment]
I would like to try handling this issue 🙋
