### ISSUE TITLE
If there is a message in Session, it would be better to display it on the TimetableItemDetailScreen as well

### ISSUE THREAD

**Issue by kosenda** [DroidKaigi/conference-app-2024#1024]
## Overview
The value “message” is included in the Timetable's information, and with TimetableList, the message can be understood, but with TimetableGrid, the message is only an icon, so it may not be possible to know the content of the message when the details are opened by tapping on it, I thought it would be better to display the message on the TimetableItemDetailScreen as well as on the TimetableList.

|TimetableList|TimetableGrid|TimetableDetail|
|---|---|---|
|<img width="300" src="https://github.com/user-attachments/assets/261d271d-4430-4786-a514-ae35c292fa59">|<img width="300" src="https://github.com/user-attachments/assets/c80a652c-8384-48bb-b8ea-742d7ff8ca18">|<img width="300" src="https://github.com/user-attachments/assets/52e76a16-17ca-4111-87d0-6f2a64103363">|

## Sample
<img src="https://github.com/user-attachments/assets/c27300a5-b259-442b-9581-861ac291e1ba" width="300">

**Comment by kosenda** [comment]
@takahirom @nobonobopurin 
How about this one...? 🙇

**Comment by takahirom** [comment]
I completely agree with you. However, as you know, we don't have the design for it right now, and we don't have much time. I think adding an 8dp margin to the left of the sample you provided would be good for me. @nobonobopurin, what do you think?

**Comment by nobonobopurin** [comment]
@takahirom @kosenda 
I agree with you! 
Regarding the left and right margins on the session detail screen, the design shows 16dp, but it's currently implemented with 8dp. So, I'm okay with adding an extra 8dp margin to the left 😂 I've also updated Figma. 

[Figma](https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI?node-id=54901-55056&t=Npm6yrOIpMB3o4t3-4)

![image](https://github.com/user-attachments/assets/add246a8-d92f-442c-96b3-f90d30919ae8)

**Comment by Corvus400** [comment]
I would like to work on this task.

**Comment by takahirom** [comment]
Thank you for addressing this high priority issue. 🙏
