### ISSUE TITLE
Apply profile card edit screen design roughly

### ISSUE THREAD

**Issue by mikanIchinose** [DroidKaigi/conference-app-2024#112]
| current | ideal |
|--------|--------|
| <img height=500 src=""> | <img width="171" alt="image" src="https://github.com/user-attachments/assets/07cc4391-66a0-41c4-88e3-27fd57f3458b"> | 

https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI?node-id=54795-26746&t=jBceLP15jxDiPfMP-0

**Comment by hiroaki404** [comment]
🙋‍♂️

**Comment by takahirom** [comment]
Thanks! Assigned 👍

**Comment by hiroaki404** [comment]
In the issue the occupation and link, image should be optional, but in Figma the optional labels seem to be erased. Which is correct?

**Comment by takahirom** [comment]
@hiroaki404 It is mandatory now. Sorry for the confusion
