### ISSUE TITLE
Apply profile card card screen design roughly

### ISSUE THREAD

**Issue by mikanIchinose** [DroidKaigi/conference-app-2024#113]
| current | ideal |
|--------|--------|
| <img height=700> | <img width="176" alt="image" src="https://github.com/user-attachments/assets/b4831014-aafe-4c8d-bb6f-73c5dc2d460d"> | 

https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI?node-id=54795-26746&t=jBceLP15jxDiPfMP-0

**Comment by Cjsghkd** [comment]
Can I try this issue? ✋

**Comment by takahirom** [comment]
Thanks! Assigned 👍
