### ISSUE TITLE
Add time display to the left side of the timetable

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2024#201]
## Overview
The current timetable view does not show time indicators such as "11:20 - 16:00" on the left side. This feature needs to be implemented to improve user experience and align with the design.
<img width="364" alt="image" src="https://github.com/user-attachments/assets/572c82af-8b0d-4112-b429-b6bf6ad45267">

## Links
- Design: https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI
- Code: https://github.com/DroidKaigi/conference-app-2024/blob/27ea36f1ae39693bbdb51c4d90e2a126551c8fc0/feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/TimetableScreen.kt#L91

**Comment by ParkJong-Hun** [comment]
🙋‍♂️

**Comment by takahirom** [comment]
Wow you are so fast! 🏎️  Thanks Assigned 👍
