### ISSUE TITLE
Favorite registration micro-interaction for Android

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2024#203]
## Overview
Implement a micro-interaction animation when tapping the favorite button on the timetable list. The animation should show a heart entering the "Favorites" tab (heart icon) in the bottom navigation from the timetable list's favorite button.

## Links
- Design: https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI

**Comment by shunm-999** [comment]
🙋　Can I take charge of this? It might take some time, though.

**Comment by takahirom** [comment]
Thanks! Assigned 👍
