### ISSUE TITLE
[iOS] Favorite registration micro-interaction for iOS

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2024#204]
## Overview
Implement a micro-interaction animation when tapping the favorite button on the timetable list. The animation should show a heart entering the "Favorites" tab (heart icon) in the bottom navigation from the timetable list's favorite button.

## Links
- Design: https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI

**Comment by fumiyasac** [comment]
I'm not sure if I can do it, but I'd like to try it 🙌

**Comment by fumiyasac** [comment]
@takahirom I tried creating a prototype. 
If this policy looks good, I'm thinking of submitting a pull request.What do you think?
https://x.com/fumiyasac/status/1830152726250238142
