### ISSUE TITLE
Add map link for Bellesalle Shibuya Garden in About screen

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2024#205]
## Overview
The About screen currently lacks a map link to Bellesalle Shibuya Garden. We need to implement this feature to improve user navigation and provide easy access to the venue location.

<img width="438" alt="image" src="https://github.com/user-attachments/assets/8087eb3f-b8fc-4047-a863-1d16ca1efc27">

## Links
- Design: https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI
- Code: https://github.com/DroidKaigi/conference-app-2024/blob/055e7d4d7fd2e529cc2a9ce6788cc1f941d35732/feature/about/src/commonMain/kotlin/io/github/droidkaigi/confsched/about/AboutScreen.kt#L81

**Comment by Corvus400** [comment]
I would like to work on this task.

**Comment by takahirom** [comment]
You are the first contributor that raise hand! 🏎️  Thanks! Assigned
