### ISSUE TITLE
Missing logos for YouTube, X, and Medium on the About screen

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2024#206]
## Description
The About screen is currently not displaying the logos for YouTube, X (formerly Twitter), and Medium. These logos should be added to enhance the visual representation of the social media links.
![image](https://github.com/user-attachments/assets/1359fdbe-e84d-4589-a659-6dc5146426de)

## Links
- Code: https://github.com/DroidKaigi/conference-app-2024/blob/055e7d4d7fd2e529cc2a9ce6788cc1f941d35732/feature/about/src/commonMain/kotlin/io/github/droidkaigi/confsched/about/AboutScreen.kt#L81
- Design: https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI

**Comment by fornewid** [comment]
🙋‍♂️

**Comment by takahirom** [comment]
Thanks as always! Assigned 👍

**Comment by fornewid** [comment]
@takahirom 
There's no vectorized icons in figma.
Can I get vectorized icons for YouTube, X, Medium?
(Or should I add png icons for this?)

**Comment by takahirom** [comment]
@fornewid I don't have a strong opinion about this. I think we can use png image for this. What do you think?

**Comment by fornewid** [comment]
Yes, it is possible. I will try to apply it as PNG.
