### ISSUE TITLE
Switch timetable view icon appropriately between list and grid views

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2024#207]
## Overview
Implement the functionality to switch the timetable view icon appropriately when toggling between list and grid views for the session timetable.
<img width="378" alt="image" src="https://github.com/user-attachments/assets/32dd8305-d67e-4db8-939f-7e502a4d77ae">

## Links
- Design: https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI
- Code: https://github.com/DroidKaigi/conference-app-2024/blob/27ea36f1ae39693bbdb51c4d90e2a126551c8fc0/feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/TimetableScreen.kt#L91

**Comment by WonJoongLee** [comment]
I want to try this one 🙋

**Comment by takahirom** [comment]
Thanks!
