### ISSUE TITLE
Align EventMap item layout with Figma design

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2024#208]
## Overview
Update the floor layout in the EventMap page to match the design in Figma.

design
<img width="239" alt="image" src="https://github.com/user-attachments/assets/2e84b264-8534-4a23-8642-9342e5b57708">

## Links
- Code: https://github.com/DroidKaigi/conference-app-2024/blob/1b0818c053c5f7c0279da90c54df0c61317b25e3/feature/eventmap/src/commonMain/kotlin/io/github/droidkaigi/confsched/eventmap/EventMapScreen.kt#L82
- Design: https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI

**Comment by Corvus400** [comment]
I've finished other tasks, so I'd like to start working on this one. 🙋

**Comment by takahirom** [comment]
Thanks! Assigned 👍
