### ISSUE TITLE
Fix "Readmore" text to "More" in session detail screen for English settings

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2024#209]
## Overview
Update the text "Readmore" to "More" in the session detail screen when the app language is set to English. This change will improve the user interface consistency and readability.
<img width="228" alt="image" src="https://github.com/user-attachments/assets/2f8ec03a-e6dc-4e74-a798-4d9a09ffc541">

## Links
- Design: https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI

**Comment by sanao1006** [comment]
I would like to work on this task.

**Comment by takahirom** [comment]
I think you can do more difficult tasks 😄 But I appreciate it! Thanks. Assigned 👍
