### ISSUE TITLE
Make profile card glow based on device orientation

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2024#210]
## Description
To provide an experience similar to holding a physical card, implement a feature that makes the profile card glow based on the device's orientation using the gyroscope sensor.

## Links
Design: https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI

**Comment by choi-woo-sung** [comment]
i want it

**Comment by takahirom** [comment]
Yeah, but it's currently blocked by the base implementation.

**Comment by takahirom** [comment]
This issue has been unblocked!

**Comment by mhidaka** [comment]
@choi-woo-sung would you still feel like do it? let me know in the comments! 

Also anyone is welcome to challenge this issue!

**Comment by shunm-999** [comment]
I want to challenge this issue!

I would like to implement a holographic effect on the card, similar to the example on the site below, where the shine changes based on the device's rotation. (similar to pokemon card)
https://dev.to/annlin/holographic-effect-on-web-39bc

Would that be okay?

**Comment by takahirom** [comment]
Looks great!

**Comment by takahirom** [comment]
Assigned 👍

**Comment by choi-woo-sung** [comment]
Oh, sorry, I wasn't able to check it because I was traveling until today. I heard it was a block, so I was in the process of making it, but I'll give it up.

**Comment by choi-woo-sung** [comment]
Can we make it together? I've had a similar experience to the function and presented it through a conference.

**Comment by shunm-999** [comment]
@choi-woo-sung 
I think it would be difficult to work together, so even though I was interested in trying it, 
I’ll hand over responsibility for this issue to you if you’re going to implement it.

**Comment by choi-woo-sung** [comment]
@shunm-999 
No, thank you for your consideration.
