### ISSUE TITLE
Session detail screen: Room and language layout slightly differs from Figma

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2024#211]
## Overview
The layout for the room and language information in the session detail screen doesn't exactly match the Figma design.

## Links
Code: https://github.com/DroidKaigi/conference-app-2024/blob/ec7c35cc7a425acaf2d86bdd9d48780268c9f5ea/feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/TimetableItemDetailScreen.kt#L81

Design: https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI

<img width="127" alt="image" src="https://github.com/user-attachments/assets/ef69cda1-c769-4e81-9a94-20fd3b3e0319">

**Comment by takathemax** [comment]
🙋

**Comment by takahirom** [comment]
Thanks! Assigned 👍
