### ISSUE TITLE
Slightly rotate profile card and first-time launch card

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2024#212]
## Overview
Implement a subtle rotation animation for the profile card and first-time launch card to indicate to users that tapping the profile card will rotate it, revealing a QR code on the back.

## Links
Design: https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI
Code: https://github.com/DroidKaigi/conference-app-2024/blob/2422784ca04d2a479189cb2ad6b3db2ec6fe349b/feature/profilecard/src/commonMain/kotlin/io/github/droidkaigi/confsched/profilecard/ProfileCardScreen.kt#L119

**Comment by Cjsghkd** [comment]
Can I try this issue? ✋

**Comment by takahirom** [comment]
Sorry. This issue is blocked by https://github.com/DroidKaigi/conference-app-2024/issues/113 for now
