### ISSUE TITLE
Display appropriate information for Welcome Talk and Lunch Break in Timetable detail screen

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2024#213]
## Overview
Currently, when tapping on Welcome Talk or Lunch Break in the Timetable screen and transitioning to the detail screen, it displays the event date, time, location, and the text "Special". We need to update this to show more appropriate information for these special session types.

## Links
- Design: https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI
- Code: https://github.com/DroidKaigi/conference-app-2024/blob/ec7c35cc7a425acaf2d86bdd9d48780268c9f5ea/feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/TimetableItemDetailScreen.kt#L81

**Comment by hiraike32** [comment]
✋🏻

**Comment by takahirom** [comment]
Thanks! Assigned 👍
