### ISSUE TITLE
Timetable item tap area is too small

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2024#214]
## Overview
The tap area for timetable items appears to be smaller than optimal. It should likely cover the entire item for better user interaction.
<img width="145" alt="image" src="https://github.com/user-attachments/assets/3aba22fd-db82-4e56-875e-00200bac8593">

## Links
Code: https://github.com/DroidKaigi/conference-app-2024/blob/27ea36f1ae39693bbdb51c4d90e2a126551c8fc0/feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/TimetableScreen.kt#L91

Design: https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI

**Comment by CookieySun** [comment]
🙋‍♂️

**Comment by takahirom** [comment]
Thanks! I think this is very important bug for users 😄  Assigned 👍
