### ISSUE TITLE
Display session message feature for Android app

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2024#217]
## Overview
Implement a feature to display session information such as cancellations using the data from TimetableItem.Session.message.
<img width="174" alt="image" src="https://github.com/user-attachments/assets/8da616bf-f6b3-425b-aa57-271ee2bc78eb">

## Links
Code: https://github.com/DroidKaigi/conference-app-2024/blob/27ea36f1ae39693bbdb51c4d90e2a126551c8fc0/feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/TimetableScreen.kt#L91

Design: https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI

**Comment by kota-shiokara** [comment]
I want to try this issue🙋

**Comment by takahirom** [comment]
Thanks! Assigned 👍
