### ISSUE TITLE
[iOS] Display session message feature for iOS app

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2024#218]
## Overview
Implement a feature to display session information such as cancellations using the data from TimetableItem.Session.message.

## Links
Design: https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI

**Comment by mltokky** [comment]
🙋🏻

**Comment by shin-usu** [comment]
@mltokky 
Thank you! Assigned.

**Comment by mltokky** [comment]
@shin-usu 

Let me confirm implementation's scope in this task.

I think grid view mode of Timetable is not implemented now, but I found exclamation mark that indicate to exist session information in design.

So, may I not implement of displaying exclamation mark in grid view mode in this task? (Will it be implemented in another task?)

**Comment by shin-usu** [comment]
@mltokky 
Yes, let us leave grid mode out of the scope of this Issue, as it has not been implemented yet.
We will create an issue when needed.
Thanks for your confirmation!
