### ISSUE TITLE
Add share functionality to session detail screen

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2024#219]
## Overview
Implement a feature that allows users to share session details with external apps when tapping the share icon on the session detail screen.

## Links
- Design: https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI
- Code: https://github.com/DroidKaigi/conference-app-2024/blob/ec7c35cc7a425acaf2d86bdd9d48780268c9f5ea/feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/TimetableItemDetailScreen.kt#L81

**Comment by hiroaki404** [comment]
🙋

**Comment by takahirom** [comment]
Thanks! Assigned!
