### ISSUE TITLE
Session detail screen: Speaker name not center-aligned next to icon

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2024#220]
## Overview
On the session detail screen, the speaker's name to the right of their icon is not center-aligned vertically. This misalignment should be corrected to match the design specifications.
<img width="163" alt="image" src="https://github.com/user-attachments/assets/c454c194-97a3-43b9-a1c6-3009ecc96586">

## Links
- Design: https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI
- Code: https://github.com/DroidKaigi/conference-app-2024/blob/ec7c35cc7a425acaf2d86bdd9d48780268c9f5ea/feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/TimetableItemDetailScreen.kt#L81

**Comment by ttanaka330** [comment]
✋

**Comment by takahirom** [comment]
Thanks! Assigned 👍
