### ISSUE TITLE
Session detail screen does not display "Date/Time, Location, Supported Languages, Category" in English when device language is set to English

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2024#221]
## Overview
When the device language is set to English, the session detail screen does not properly localize the "Date/Time, Location, Supported Languages, Category" information into English. This inconsistency affects the user experience for English-speaking users.

<img width="210" alt="image" src="https://github.com/user-attachments/assets/29dc08a2-1321-476f-9bea-c43243d51b19">

## Links
Code: https://github.com/DroidKaigi/conference-app-2024/blob/ec7c35cc7a425acaf2d86bdd9d48780268c9f5ea/feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/TimetableItemDetailScreen.kt#L81

Design: https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI

**Comment by WonJoongLee** [comment]
✋

(I've already made a PR; I didn't know I had to raise my hand. 😅)

**Comment by takahirom** [comment]
It's fine! But if someone raises their hand first, we may need to prioritize that person. So it's better to raise your hand before you start working on the development.
