### ISSUE TITLE
Add grid item border to timetable grid view

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2024#222]
## Overview
The current timetable grid view lacks border lines. We need to add these lines to match the design specifications.

<img width="347" alt="image" src="https://github.com/user-attachments/assets/481b5b97-1a83-4fed-8405-ee00589023f9">

## Links
- Code: https://github.com/DroidKaigi/conference-app-2024/blob/27ea36f1ae39693bbdb51c4d90e2a126551c8fc0/feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/TimetableScreen.kt#L91
- Design: https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI

**Comment by risako070310** [comment]
🖐️

**Comment by takahirom** [comment]
Thanks! Assigned 👍

**Comment by takahirom** [comment]
@risako070310 Are you still up for this? 👀

**Comment by risako070310** [comment]
@takahirom I am currently working on this issue here. Please give a little more time.

**Comment by risako070310** [comment]
@takahirom 
I think someone do this issue in another commitment. Now, may I close this issue?
<img width="300" src="https://github.com/user-attachments/assets/9ab60c1d-316f-4199-956c-7948211f5d87">

**Comment by takahirom** [comment]
Sorry, I didn't notice this change. 🙇
