### ISSUE TITLE
Implement the app bar "About DroidKaigi" in the About list screen

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2024#223]
## Overview
Implement the app bar with the text "About DroidKaigi" in the About list screen of the DroidKaigi 2024 app.

<img width="123" alt="image" src="https://github.com/user-attachments/assets/c24a0d4e-3871-4206-a499-6c08df5e12ea">

## Links
- Design: https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI
- Code: https://github.com/DroidKaigi/conference-app-2024/blob/055e7d4d7fd2e529cc2a9ce6788cc1f941d35732/feature/about/src/commonMain/kotlin/io/github/droidkaigi/confsched/about/AboutScreen.kt#L81

**Comment by sanao1006** [comment]
I would like to work on this task!

**Comment by takahirom** [comment]
You are trying medium issue now! Thanks!
