### ISSUE TITLE
Inconsistent speaker icon shape in timetable grid

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2024#224]
## Description
The speaker icons in the timetable grid are currently displayed as squares, but they should be circular according to the design.

<img width="379" alt="image" src="https://github.com/user-attachments/assets/cac2d589-3165-44cd-a350-e54a205efff2">

## Links
- Design: https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI
- Code: https://github.com/DroidKaigi/conference-app-2024/blob/27ea36f1ae39693bbdb51c4d90e2a126551c8fc0/feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/TimetableScreen.kt#L91

**Comment by SEKI-YUTA** [comment]
:raising_hand:

**Comment by takahirom** [comment]
Thanks! Assigned 👍 I'm looking forward to your contribution!
