### ISSUE TITLE
Reverse title and time in timetable grid

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2024#225]
## Overview
The current implementation of the timetable grid displays the title and time in reverse order compared to the design. This needs to be corrected to match the design specifications.
<img width="538" alt="image" src="https://github.com/user-attachments/assets/e9377897-0760-494b-b155-c998f8845bec">

## Links
- Design: https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI
- Code: https://github.com/DroidKaigi/conference-app-2024/blob/27ea36f1ae39693bbdb51c4d90e2a126551c8fc0/feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/TimetableScreen.kt#L91

**Comment by TomoyaShibata** [comment]
✋

**Comment by takahirom** [comment]
Thanks as always! Assigned 👍
