### ISSUE TITLE
Adjust spacing between Bottom Navigation items

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2024#226]
## Overview
The spacing between items in the Bottom Navigation bar is currently too narrow. We need to widen it to match the design specifications.

<img width="628" alt="image" src="https://github.com/user-attachments/assets/0d80a129-e4f8-4acf-b326-1fe079d2636f">

## Links
- Design: https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI
- Code: https://github.com/DroidKaigi/conference-app-2024/blob/35ff30ea65796d02a286f1f2fd3623bce7a74e15/feature/main/src/commonMain/kotlin/io/github/droidkaigi/confsched/main/MainScreen.kt#L175

**Comment by garijp** [comment]
🙋

**Comment by takahirom** [comment]
Thanks! Assigned 👍
