### ISSUE TITLE
Change text color to green in About screen

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2024#227]
## Description
Update the text color to green in the About screen of the DroidKaigi 2024 app.
<img width="114" alt="image" src="https://github.com/user-attachments/assets/e9806343-596f-4ccb-9037-a37b3e21e34d">

## Links
- Design: https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI
- Code: https://github.com/DroidKaigi/conference-app-2024/blob/055e7d4d7fd2e529cc2a9ce6788cc1f941d35732/feature/about/src/commonMain/kotlin/io/github/droidkaigi/confsched/about/AboutScreen.kt#L81

**Comment by Lilin-18th** [comment]
:raising_hand:

**Comment by takahirom** [comment]
Thanks! Assigned 👍

**Comment by takahirom** [comment]
It looks like this implementation is needed in advance. Please wait a little.
https://github.com/DroidKaigi/conference-app-2024/pull/269

**Comment by takahirom** [comment]
@Lilin-18th 
It looks like this implementation is needed in advance. Please wait a little.
https://github.com/DroidKaigi/conference-app-2024/pull/269

**Comment by takahirom** [comment]
Thank you for your patience. We've merged the theme. Please update your development branch with the remote main branch to use the updated color scheme.
