### ISSUE TITLE
Center align title in Staff screen app bar when it's in small state

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2024#228]
## Overview
When the app bar in the Staff screen is in its small state, the title should be center-aligned for better visual consistency and user experience.
<img width="246" alt="image" src="https://github.com/user-attachments/assets/86d21530-5664-4e11-bfe7-c4497107a4e9">

## Links
- Design: https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI
- Code: https://github.com/DroidKaigi/conference-app-2024/blob/77226c43d551c07bba9f35ba8becef25b2e271d3/feature/staff/src/commonMain/kotlin/io/github/droidkaigi/confsched/staff/StaffScreen.kt#L68

**Comment by kosenda** [comment]
🙋

**Comment by takahirom** [comment]
Thanks! Assigned 👍
