### ISSUE TITLE
Add a background by using Surface for TimetablePreview

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2024#242]
## Overview
The background should be black, but the TimetablePreview has a transparent background. It is difficult to check the design. Could we add a Surface to TimetablePreview that uses an appropriate background color?

<img width="818" alt="image" src="https://github.com/user-attachments/assets/66324ead-fc68-4c8d-9026-bee81d98d1f8">

**Comment by Nagumo-7960** [comment]
I would like to work on this task🙋‍♂️

**Comment by takahirom** [comment]
I saw your comment about the DroidKaigi app on X! Thanks! I've assigned this task to you. 👍
