### ISSUE TITLE
Implement shared element transitions between the timetable list and timetable item details.

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2024#243]
This year we have shared element transition in Compose! We don't have "the shared element" but we could use container. I think we can make the item container bigger and set the visibility alpha to zero. I think we can use `sharedBounds()` instead of `sharedElement()`

**Comment by gibachan** [comment]
I would like to take this issue 🙋

**Comment by takahirom** [comment]
Thank you for raising hand! Assigned 👍
