### ISSUE TITLE
 Centering the app bar on the About list screen when scrolling

### ISSUE THREAD

**Issue by sanao1006** [DroidKaigi/conference-app-2024#275]
## Overview 
This Issue is related to #223, PR  #270.

According to [figma](https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI?node-id=55725-8670&t=htgSgF3wWucKlsEr-0), The text on the TopAppBar on the About List screen is located on the left edge.
![image](https://github.com/user-attachments/assets/31400471-8027-4af1-9596-cdc9d029d787)

**However**, the text on the TopAppBar must be centered on the screen when **scrolled** ([figma](https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI?node-id=54982-75342&t=htgSgF3wWucKlsEr-0))

![image](https://github.com/user-attachments/assets/b08a35c4-63a0-4315-b748-c9fc82686ef2)

What we will probably have to do is
1. detect scrolling
2. center the text
    - Ideally, use animation to make it move smoothly

**Comment by chattymin** [comment]
🙋‍♂️

**Comment by takahirom** [comment]
Thanks! Assigned 👍

**Comment by takahirom** [comment]
We don't have a solution for this. However, there is a similar issue.
https://github.com/DroidKaigi/conference-app-2024/issues/228

**Comment by chattymin** [comment]
> We don't have a solution for this. However, there is a similar issue. #228

Once this issue is resolved, should I reuse the existing component, or is it okay for me to implement that part as well?
