### ISSUE TITLE
Prevent speaker icons being flat in screenshot tests

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2024#279]
It appears that the speaker icons look flat when the item is small.
<img width="962" alt="image" src="https://github.com/user-attachments/assets/f46afba8-eb84-48e6-a48a-601a9e14f1ec">

https://github.com/DroidKaigi/conference-app-2024/pull/276

**Comment by kosenda** [comment]
I'd like to do this 🙋

**Comment by kosenda** [comment]
Is it OK to reduce the size of the speaker icons?
I'm wondering if this is happening because there is no problem with the screenshot test and simply the vertical size is not enforced.

**Comment by takahirom** [comment]
Thanks! I think we don't have any spec here. If you cloud find a good presentation, it would be great.

**Comment by takahirom** [comment]
Anyway, I assigined you!👍
