### ISSUE TITLE
Add TimetableItemDetailScreenTest checks

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2024#282]
We can run the test by clicking the "Run" button on the left side of Android Studio.

<img width="144" alt="image" src="https://github.com/user-attachments/assets/c7b29374-cc0b-4f67-a667-b5cfd73a41bf">

Please add some test checks for the TimetableItemDetailScreen.
The current code looks like this:

```kotlin
                    describe("click first session bookmark") {
                        run {
                            clickFirstSessionBookmark()
                        }
                        itShould("show bookmarked session") {
                            // FIXME: Add check for bookmarked session
                            captureScreenWithChecks()
                        }
                    }
```

We would like to add some checks similar to other tests. Please add a check like `checkBookmarkedSessionDisplayed()` in the robot and implement it.

```kotlin
                    itShould("show timetable items") {
                        captureScreenWithChecks(checks = {
                            checkTimetableItemsDisplayed()
                        })
                    }
```

It looks like there are 7 checks to fix in the TimetableItemDetailScreenTest.

https://github.com/DroidKaigi/conference-app-2024/blob/0a15d6b930e981217645ecd0d1be5bde4d412f22/feature/sessions/src/androidUnitTest/kotlin/io/github/droidkaigi/confsched/sessions/TimetableItemDetailScreenTest.kt#L58-L59

**Comment by Corvus400** [comment]
I've finished other tasks, so I'd like to start working on this one. 🙋

**Comment by takahirom** [comment]
@Corvus400 Thanks! Assigned 👍
