### ISSUE TITLE
Migrate AppStrings to compose multiplatform resources

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2024#287]
It looks easy but It is used a little tricky place. Could we replace it with compose multiplatform resources?
Please refer to [SessionRes](https://github.com/DroidKaigi/conference-app-2024/blob/0ade008ede17c29305f51a4523270f552494c958/feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/SessionsRes.kt#L5) and [strings.xml](https://github.com/DroidKaigi/conference-app-2024/blob/0ade008ede17c29305f51a4523270f552494c958/feature/sessions/src/commonMain/composeResources/values/strings.xml) to replace.

https://github.com/DroidKaigi/conference-app-2024/blob/5fdceb4daaa927cadeca84d5c6327d379bc2a4b7/core/designsystem/src/commonMain/kotlin/io/github/droidkaigi/confsched/designsystem/strings/AppStrings.kt#L3

**Comment by Corvus400** [comment]
I've finished other tasks, so I'd like to start working on this one. 🙋

**Comment by takahirom** [comment]
Thanks! Assigned 👍
