### ISSUE TITLE
Migrate MainStrings to compose multiplatform resources

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2024#288]
Please refer to [SessionRes](https://github.com/DroidKaigi/conference-app-2024/blob/0ade008ede17c29305f51a4523270f552494c958/feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/SessionsRes.kt#L5) and [strings.xml](https://github.com/DroidKaigi/conference-app-2024/blob/0ade008ede17c29305f51a4523270f552494c958/feature/sessions/src/commonMain/composeResources/values/strings.xml) to replace.

https://github.com/DroidKaigi/conference-app-2024/blob/2e9f6c38a9b1f7772db5593be4ae2166e8d58686/feature/main/src/commonMain/kotlin/io/github/droidkaigi/confsched/main/strings/MainStrings.kt#L7

**Comment by ked4ma** [comment]
I'll try it :raised_back_of_hand: 

and I have one question.
you said "SectionRes" but is it "MainRes" what you wanted to use?

**Comment by takahirom** [comment]
I thought we don't have MainRes. So I mentioned the SessionsRes. We would like to use MainRes for sure!

**Comment by ked4ma** [comment]
I found MainRes in the same module of MainStrings and  it seems same impl like SessionRes.
https://github.com/DroidKaigi/conference-app-2024/blob/main/feature/main/src/commonMain/kotlin/io/github/droidkaigi/confsched/main/MainRes.kt

> We would like to use MainRes for sure!

I see! so I would like to use it!
