### ISSUE TITLE
Add a TimetableScreenTest to verify the display of the 9/13 tab

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2024#290]
We can run the test by clicking the "Run" button on the left side of Android Studio.

<img width="144" alt="image" src="https://github.com/user-attachments/assets/c7b29374-cc0b-4f67-a667-b5cfd73a41bf">

The test flow should involve clicking the tab and checking the displayed sessions.

https://github.com/DroidKaigi/conference-app-2024/blob/0a15d6b930e981217645ecd0d1be5bde4d412f22/feature/sessions/src/androidUnitTest/kotlin/io/github/droidkaigi/confsched/sessions/TimetableScreenTest.kt#L60-L67

**Comment by ked4ma** [comment]
:raised_back_of_hand:

**Comment by takahirom** [comment]
Thanks! Assigned!
