### ISSUE TITLE
Bump targetSdk version to 34

### ISSUE THREAD

**Issue by NUmeroAndDev** [DroidKaigi/conference-app-2024#301]
## Overview
- After August 31, 2024, any app releases or updates will require targetSdk version 34, but this app has targetSdk version 33.
- The definition can be found here.
  - https://github.com/DroidKaigi/conference-app-2024/blob/9b090cfd47b6427c9d3e55da618701d7738ddcd6/build-logic/src/main/kotlin/io/github/droidkaigi/confsched/primitive/AndroidGradleDsl.kt#L38
- We should be able to launch the app without crashing. However, it doesn't need to be perfect.

## Link
- https://support.google.com/googleplay/android-developer/answer/11926878?hl=en&sjid=11494528915384632195-AP

**Comment by rnitame** [comment]
🙋‍♀️

**Comment by NUmeroAndDev** [comment]
Thanks! Assigned 👍
