### ISSUE TITLE
Remove intent filter of HiltTestActivity

### ISSUE THREAD

**Issue by NUmeroAndDev** [DroidKaigi/conference-app-2024#302]
## Overview
- `HiltTestActivity` is included in the debug build, so the launcher app shows two app icons.
  - https://github.com/DroidKaigi/conference-app-2024/blob/2b45509643ed4ccfceabb4d622bffd93d72d0f58/app-android/build.gradle.kts#L114
 
<img src="https://github.com/user-attachments/assets/1d4c0821-bbe8-4694-a45d-7510d0ab43e7" width="200px" />

- ~~I don't think HiltTestActivity needs to be included in the debug build(may only test build), but I'm not sure if it's okay to remove it from the debug build.~~
- I want to removing `HiltTestActivity` intent filter for the launcher.

**Comment by NUmeroAndDev** [comment]
@takahirom 
If you know anything about this, please add comments. 🙏

**Comment by takahirom** [comment]
Thank you for your suggestion! The activity is needed in debug source sets to register Activity for tests. But I think the intent filter of Activity is not needed.

**Comment by NUmeroAndDev** [comment]
I see, I understand. 🙏 
I changed this issue to change the intent filter so that it doesn't appear in the launcher.

**Comment by Tomoyuki-TAKEZAKI** [comment]
Hello!
I'd like to work on this issue. 🙋🏻

**Comment by takahirom** [comment]
Thanks, Assigined!👍
