### ISSUE TITLE
When entering the EventMap screen, the Back button on the AppBar is not necessary.

### ISSUE THREAD

**Issue by sanao1006** [DroidKaigi/conference-app-2024#303]
## Overview
Currently, the BackButton is placed in the AppBar of the EventMap screen.
![image](https://github.com/user-attachments/assets/02a7a90d-acf2-43fd-8bf6-41de4b3f944b)

However, according to [Figma design](https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI?node-id=54953-63681&t=Leo2xx2mUbK3AGwU-0), the BackButton on the AppBar of the EventMap screen is only necessary when scrolling.
Therefore, this should be removed.
First View | Scroll | 
:--: | :--: |
|<img src="https://github.com/user-attachments/assets/642516fb-32b0-418c-9a56-16542640213d" width=300 />|![image](https://github.com/user-attachments/assets/7640803c-7492-45b5-8c11-e7c6093e644e)|

### Suggestion
- Back button installation should be unified.
- First of all, perhaps we don't need a back button on this screen(?)

**Comment by takahirom** [comment]
@nobonobopurin 
I think you forget to remove the back button. Is that right?👀

**Comment by nobonobopurin** [comment]
@sanao1006 @takahirom Yes, I missed removing the back button, but I've just taken care of it now.
![Scroll-03](https://github.com/user-attachments/assets/a12d461f-95a1-41e4-ab35-29dc5f287b13)

**Comment by takahirom** [comment]
@sanao1006 If you want to remove the back button. I'll assign this issue to you 👍

**Comment by sanao1006** [comment]
@takahirom 
Thank you!
I will take care of this issue!

**Comment by takahirom** [comment]
Thanks. Assigned 👍
