### ISSUE TITLE
Prevent multiple transitions

### ISSUE THREAD

**Issue by kosenda** [DroidKaigi/conference-app-2024#306]
## OverVIew
I thought it would be good if it could be prevented because tapping the transitionable buttons at the same time causes a transition to each screen.

https://github.com/user-attachments/assets/dc5cbc8e-b9b0-4d1c-892c-5bbd9338f492

## Ref
- I think that this can be somewhat easily prevented by using `dropUnlessResumed` in `androidx.lifecycle:lifecycle-runtime-compose`.
  - https://developer.android.com/reference/kotlin/androidx/lifecycle/compose/package-summary#dropUnlessResumed(androidx.lifecycle.LifecycleOwner,kotlin.Function0)

**Comment by takahirom** [comment]
I didn't know that looks great!

**Comment by takahirom** [comment]
We might have to think about where to call the dropUnlessResumed. Could we wrap by dropUnlessResumed and pass the labmda?

**Comment by kosenda** [comment]
It was a recognition that can be made…!

**Comment by takahirom** [comment]
I'm looking for a person who want to do this!

**Comment by nashcft** [comment]
I'd like to try this issue 🙋

**Comment by takahirom** [comment]
Thanks! Assigned 👍

**Comment by kosenda** [comment]
@takahirom 
I think the assignment will be @nashcft 🙇

**Comment by takahirom** [comment]
My bad! Reassigned!🙏
