### ISSUE TITLE
Timeline detail background is broken if title is too short and speakers are nothing in iOS App

### ISSUE THREAD

**Issue by shimastripe** [DroidKaigi/conference-app-2024#307]
## Problem

- Timeline detail header background is broken if title is too short and speakers are nothing in iOS App.

Current states are below.

|OK Case|NG Case|
|---|---|
|![Simulator Screenshot - iPhone 15 Pro - 2024-08-12 at 00 07 23](https://github.com/user-attachments/assets/d2ff1755-3be8-4c3e-a41e-c09e6f4cb699)|![Simulator Screenshot - iPhone 15 Pro - 2024-08-12 at 00 07 18](https://github.com/user-attachments/assets/204c9041-a708-488a-a2c3-9b168cbb3296)|

## How to fix

|OK Case|**Desired**|
|---|---|
|![Simulator Screenshot - iPhone 15 Pro - 2024-08-12 at 00 03 47](https://github.com/user-attachments/assets/7c915fa5-45cd-4a73-80bd-b570b094014c)|![Simulator Screenshot - iPhone 15 Pro - 2024-08-12 at 00 03 43](https://github.com/user-attachments/assets/62f3cb94-97ab-4405-b54b-17f9062f23e3)|

**Comment by shin-usu** [comment]
@shimastripe 
Thank you very much for creating the Issue🙏🏻 
Text and chip are leading aligned correct.

**Comment by shimastripe** [comment]
@shin-usu Thank you for giving me the correct spec! I fixed it. Can you check it please?

|OK Case|Fixed|
|---|---|
|![Simulator Screenshot - iPhone 15 Pro - 2024-08-12 at 00 51 01](https://github.com/user-attachments/assets/efbc1d70-912f-4d0b-b047-74eb01cfa896)|![Simulator Screenshot - iPhone 15 Pro - 2024-08-12 at 00 50 59](https://github.com/user-attachments/assets/870ce0c9-52c1-4f55-95ec-3c04176adf9f)|
