### ISSUE TITLE
Both sidebar and bottom nav bar displayed simultaneously

### ISSUE THREAD

**Issue by CookieySun** [DroidKaigi/conference-app-2024#312]
# Problem

Both sidebar and bottom nav bar displayed on Pixel Fold's main screen.
<img src="https://github.com/user-attachments/assets/58cdc0c6-f553-47c2-b20e-268bb2f323e1" width=500/>

# How to fix

we should remove the bottom navigation bar on large screen devices, such as the Pixel Fold's main screen. This will eliminate redundant navigation and provide a better UI.
<img src="https://github.com/user-attachments/assets/455fb649-1f4a-42a5-9a2d-3149a9c1a678" width=500/>

**Comment by takahirom** [comment]
We don't have a design for tablets. We need to think about this.

**Comment by takahirom** [comment]
When using a navigation rail, it's better to use icons instead of buttons.
https://m3.material.io/components/navigation-rail/overview

**Comment by CookieySun** [comment]
I try it!

**Comment by takahirom** [comment]
Thanks, Assigined!👍
