### ISSUE TITLE
Bottom bar overlaps the bottom list item of Favorites

### ISSUE THREAD

**Issue by Aniokrait** [DroidKaigi/conference-app-2024#314]
# Overview
Main screen's bottom bar overlaps the bottom list item in favorites screen, while timetable is not like that.
Bottom padding should be added.  

<img src="https://github.com/user-attachments/assets/07f52eb1-7c53-4e5f-9462-a8306337a08d" width="40%"/>

**Comment by Aniokrait** [comment]
I will try this ✋.

**Comment by fumiyaki** [comment]
🗽

**Comment by Corvus400** [comment]
Sorry, I thought this issue was included in the task I was in charge of, so I corrected it. :bow:
https://github.com/DroidKaigi/conference-app-2024/pull/320

**Comment by Aniokrait** [comment]
@Corvus400 
Thank you for letting me know!
EventMap screen seems to be resolved by your task, but I guess Favorite screen is still needed to be fixed.

I think I should rename the issue title and overview.

**Comment by takahirom** [comment]
Thank you for adjusting the issue! Assigned 👍
