### ISSUE TITLE
Could we standardize AnimatedLargeTopAppBar and AnimatedSmallTopAppBar using the Slot API pattern?

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2024#338]
I think the main difference between these components is the use of a back button. So I think we could apply the Slot API pattern here.

**Comment by furusin** [comment]
i'd like to try this issue 🙋‍♀️ 
Had the AnimatedSmallTopAppBar been renamed to AnimatedTextTopAppBar? I couldn't find it.

**Comment by takahirom** [comment]
AnimatedTextTopAppBar is the correct name. Thanks! Assigned 👍

**Comment by cardseditor** [comment]
@furusin 
FYI: I'd like to inform you that changes involving the use of `AnimatedTextTopAppBar` have been merged into the main branch, in relation to this issue.

**Comment by furusin** [comment]
I'm sorry to be late. I've been reading both of codes.  
AnimatedLargeTopAppBar and AnimatedSmallTopAppBar use different composable function inside of them like LargeTopAppBar and TopAppBar. This is why I think we don't have to standardize them.

@takahirom what do you think?

**Comment by takahirom** [comment]
If they are different components, I don't think we need to merge them. 👍  
Let's close then.
