### ISSUE TITLE
Bug: Unexpected scroll position sharing between tabs

### ISSUE THREAD

**Issue by CookieySun** [DroidKaigi/conference-app-2024#340]
# Problem

We have identified a bug in the tab navigation system. The issue manifests as follows:

When scrolling in the 9/12 tab and then opening the 9/13 tab, the content is not displayed at the top but rather at the scrolled position.
This behavior also occurs in reverse: scrolling in the 9/13 tab affects the scroll position when switching back to the 9/12 tab.

It appears that the scroll position is being shared between tabs, which is not the intended behavior. Each tab should maintain its own independent scroll position.

https://github.com/user-attachments/assets/bf0a7c4f-51d1-4e17-8f8a-bbed7bc608c2

**Comment by ked4ma** [comment]
let me try it :raised_hand_with_fingers_splayed:

**Comment by takahirom** [comment]
Thanks! Assigned 👍
