### ISSUE TITLE
Bug: When you move to the bottom navigation and then go back, the bottom navigation tab does not change.

### ISSUE THREAD

**Issue by Cjsghkd** [DroidKaigi/conference-app-2024#344]
## Problem
We have identified a bug in the bottom navigation system. The issue manifests as follows:

After moving to another screen using the bottom navigation bar, when you press back to return to the main screen, the bottom navigation bar tab does not change to the main screen. 
(It is the main screen, but the screen tab that was moved before going back is maintained.)

https://github.com/user-attachments/assets/0ab9115f-8d22-49b9-91b3-275251a7e079

**Comment by takahirom** [comment]
Thanks. This has been fixed in https://github.com/DroidKaigi/conference-app-2024/pull/317

**Comment by hiroaki404** [comment]
My guess is that it is resolved when going to the sub screen and back, but not resolved or degreased for the screen at the top of the tab.

**Comment by hiroaki404** [comment]
I try this
