### ISSUE TITLE
Remove blur effect of BottomBarTabs for older Android versions

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2024#345]
The current version looks like this
<img width="414" alt="image" src="https://github.com/user-attachments/assets/cb2551c9-7c7c-439b-bc46-e2f1d7b61cd3">

**Comment by mannodermaus** [comment]
I can take care of this. What do we want it to look like? Any particular preference for a color in the scheme? @nobonobopurin

**Comment by mannodermaus** [comment]
I opted for the scrim color defined in the theme (it's pure black, same as the current hardcoded value), but remove the alpha on devices without blur support. PR incoming

**Comment by nobonobopurin** [comment]
@mannodermaus  Thank you for your comment. Please use the same color as the background color of the bottom navigation. (pure black)
