### ISSUE TITLE
Add background for EventMapItemPreview screenshot testing

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2024#346]
You can see how it run.
https://github.com/DroidKaigi/conference-app-2024?tab=readme-ov-file#how-to-check-composable-preview

I think we can add `Surface` for the Preview Composable function.

<img width="764" alt="image" src="https://github.com/user-attachments/assets/9deb201d-08a0-44e3-a8fd-72b493e48c92">

**Comment by ghtoui** [comment]
I would like to challenge this! 🙋

**Comment by takahirom** [comment]
Thanks!
