### ISSUE TITLE
Fix TODOs in StaffScreenTest

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2024#351]
We can run the test by clicking the "Run" button on the left side of Android Studio.

<img width="144" alt="image" src="https://github.com/user-attachments/assets/c7b29374-cc0b-4f67-a667-b5cfd73a41bf">

https://github.com/DroidKaigi/conference-app-2024/blob/0a15d6b930e981217645ecd0d1be5bde4d412f22/feature/staff/src/androidUnitTest/kotlin/io/github/droidkaigi/confsched/staff/StaffScreenTest.kt#L53

You can refer to this PR to fix this issue

https://github.com/DroidKaigi/conference-app-2024/pull/304/files

**Comment by Corvus400** [comment]
I've finished other tasks, so I'd like to start working on this one. 🙋

**Comment by takahirom** [comment]
Thanks! Assigned 👍
