### ISSUE TITLE
Pinching in on a TimetableGrid causes the item's text, etc. to disappear

### ISSUE THREAD

**Issue by kosenda** [DroidKaigi/conference-app-2024#359]
## Overview
When I pinch in on the Grid, text, etc. disappears.
Personally, I think the title should always be prioritized for display.

https://github.com/user-attachments/assets/bb49ff6d-62f9-441f-aef4-31a50a669f37

**Comment by kosenda** [comment]
I would like to do this 🙋

**Comment by takahirom** [comment]
Thanks! Assigned 👍
