### ISSUE TITLE
In FavoriteScreen, the behavior is different from last year when there are no more items that can be displayed as a result of filtering.

### ISSUE THREAD

**Issue by kosenda** [DroidKaigi/conference-app-2024#360]
## Overview
If the different behavior is not a problem, please close 🙇

The behavior when there were no favorites in the first place was the same, but when there were favorites but filtered, the behavior was different as shown in the following video.

|2023|2024|
|---|---|
|When there are favorites but no items that can be filtered and displayed, it indicates that there are no favorites|If there are favorites but no items that can be filtered and displayed, nothing will be displayed|
|<video src="https://github.com/user-attachments/assets/b36c129a-85fe-4ccc-85c0-380a1d004f85">|<video src="https://github.com/user-attachments/assets/0a628d0f-0e90-448a-8212-c4cbc57baf28">|

**Comment by mattukouta** [comment]
I'd like to try this issue. 🙋‍♂️

**Comment by takahirom** [comment]
Thanks! Assigned 👍
