### ISSUE TITLE
ProfileCard: improve first launch UX when profilecard already saved

### ISSUE THREAD

**Issue by mikanIchinose** [DroidKaigi/conference-app-2024#371]
## Background
Currently, when we visit the profile card screen and have a profile card, the edit screen is shown for 1 frame or more.

https://github.com/user-attachments/assets/ec8add67-c3e1-4966-b47d-c5bd51b873ea

## Spec
When navigating to the profile card screen while a profile card is already saved, ensure that the screen does not flicker.

**Comment by Corvus400** [comment]
I've finished other tasks, so I'd like to start working on this one. 🙋
