### ISSUE TITLE
Wrap with captureWithChecks{} for checkTimetableListFirstItemNotDisplayed tests

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2024#375]
We can run the test by clicking the "Run" button on the left side of Android Studio.

<img width="144" alt="image" src="https://github.com/user-attachments/assets/c7b29374-cc0b-4f67-a667-b5cfd73a41bf">

I think the screenshots helps our debugging.

https://github.com/DroidKaigi/conference-app-2024/blob/237294f45e71867796d4d8427c52a553887630d6/feature/sessions/src/androidUnitTest/kotlin/io/github/droidkaigi/confsched/sessions/TimetableScreenTest.kt#L74

https://github.com/DroidKaigi/conference-app-2024/blob/237294f45e71867796d4d8427c52a553887630d6/feature/sessions/src/androidUnitTest/kotlin/io/github/droidkaigi/confsched/sessions/TimetableScreenTest.kt#L102

**Comment by pvcresin** [comment]
I would like to do this 🙋

**Comment by takahirom** [comment]
Thanks! Assigned 👍
