### ISSUE TITLE
EventMap, SponsorsList cuts off both horizontal ends when displaying Overscroll in Ripple

### ISSUE THREAD

**Issue by kosenda** [DroidKaigi/conference-app-2024#381]
## Overview
As the title says...
This phenomenon occurs when padding is used in the LazyColumn modifier, and can be resolved by using the LazyColumn argument "contentPadding".

https://github.com/user-attachments/assets/2eac1f06-a846-447a-aa04-dc6ca827f560

**Comment by amaninfo75** [comment]
#381

**Comment by ked4ma** [comment]
:raised_hand_with_fingers_splayed:

**Comment by takahirom** [comment]
Thanks! Assigend

**Comment by amaninfo75** [comment]
a80fd0888264567ca892d163719d102fae8efb32
