### ISSUE TITLE
Use this year's Sponsor API

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2024#385]
It will be `/events/droidkaigi2024/sponsor`

https://github.com/DroidKaigi/conference-app-2024/blob/a3d0c2a8e928b1c5c35c454086321535ded66a52/core/data/src/commonMain/kotlin/io/github/droidkaigi/confsched/data/sponsors/SponsorsApiClient.kt#L18

And please comment in the API and check the screen.
https://github.com/DroidKaigi/conference-app-2024/blob/a3d0c2a8e928b1c5c35c454086321535ded66a52/core/data/src/commonMain/kotlin/io/github/droidkaigi/confsched/data/sponsors/SponsorsApiClient.kt#L31-L33

**Comment by amaninfo75** [comment]
#2024

**Comment by takahirom** [comment]
Thanks! Assigned!

**Comment by takahirom** [comment]
@matsumo0922 Do you have time to work on this? 👀 This is a high-priority feature.

**Comment by matsumo0922** [comment]
Sorry for the late...
I couldn't find the time for personal reasons.

I just submitted the PR now 👍 
#523
