### ISSUE TITLE
 In TimetableItemDetailScreen, behavior of TopAppBar is different from Figma.

### ISSUE THREAD

**Issue by kosenda** [DroidKaigi/conference-app-2024#387]
## Overview
- With [Figma](https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI?node-id=54901-57963&t=wSTr1beNMpGL4sN6-4) , if you scroll down about the middle of the page, you see the TopAppBar, but now you have to scroll to the top of the page to see it.

|Figma|actual|
|---|---|
|<img width="300" alt="image" src="https://github.com/user-attachments/assets/afff0e30-490c-4df2-b6c1-aabe2eb05b49">|<video src="https://github.com/user-attachments/assets/c4323b29-dc8b-47f4-8ae3-f30acfe7f540">|

**Comment by Corvus400** [comment]
I've finished other tasks, so I'd like to start working on this one. 🙋
