### ISSUE TITLE
Switch between Filled and Outlined icons based on selection state

### ISSUE THREAD

**Issue by yumayuma708** [DroidKaigi/conference-app-2024#393]
## overview
- On Figma, icons change to Filled when selected, but in the current app, this change is not implemented. 
- Additionally, some icons in the app do not match the core icons used in Figma.

Figma | actual
--- | ---
<img width="500" alt="スクリーンショット 2024-08-14 0 26 59" src="https://github.com/user-attachments/assets/8045e6e7-5a66-40ec-a6e2-084896e72c5e"> | <img width="400" alt="スクリーンショット 2024-08-14 0 29 07" src="https://github.com/user-attachments/assets/42a39870-14fc-4c72-8553-d4ea40e87623">

**Comment by takahirom** [comment]
I was going to make the issue for this 😄  Thanks!
https://github.com/DroidKaigi/conference-app-2024/pull/390#issuecomment-2286481370
