### ISSUE TITLE
Align AboutDroidKaigi section design with Figma

### ISSUE THREAD

**Issue by chnotchy** [DroidKaigi/conference-app-2024#397]
## Overview

- The design of the AboutDroidKaigi section currently differs from the Figma design specifications.
- We need to update the font family, borders, colors, and other design elements to match the Figma design.

Figma | actual
--- | ---
<img src="https://github.com/user-attachments/assets/2fc6ca2b-7e3d-4266-85e0-2eb8051e9613" width="300" /> | <img src="https://github.com/user-attachments/assets/624f3ffd-8c72-4790-ad25-3e1b2d9ebfaa" width="300" />

**Comment by chnotchy** [comment]
I want to try this issue ✋

**Comment by takahirom** [comment]
Thanks! Assigned 👍
