### ISSUE TITLE
Add message for event map event

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2024#403]
What we need to do:
Map the message field to EventMapEvent using MultiLangText and display it in the EventMap.

<img width="308" alt="image" src="https://github.com/user-attachments/assets/9ad3ac2f-2d6a-49f0-a3d2-d521fa4331bc">

https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI?node-id=54795-26746&t=hodJGK4oqUdg4vRA-0

Note: The Event Map API has not been created yet. However, I believe we can proceed using mocks.
We already have the message field in the response class.

https://github.com/DroidKaigi/conference-app-2024/blob/9e67549610bf4c061d32d4c2f2b9394bb453f566/core/data/src/commonMain/kotlin/io/github/droidkaigi/confsched/data/eventmap/response/EventResponse.kt#L9

**Comment by YusukeSuzuki1213** [comment]
🙋

**Comment by takahirom** [comment]
Thanks! Assigned 👍
