### ISSUE TITLE
Suggestion for displaying network errors In ContributorsScreen and StaffScreen

### ISSUE THREAD

**Issue by kosenda** [DroidKaigi/conference-app-2024#404]
## Overview
I thought it would be nice to be able to give out something other than the title when the network has an error, such as offline...!
(Nothing was shown for 2023 as well as the present when offline)

|ContributorsScreen|StaffScreen|
|---|---|
|<img src="https://github.com/user-attachments/assets/3a9d120e-0c66-4757-b861-8cc03320841b" width="300">|<img src="https://github.com/user-attachments/assets/d0256493-db9f-4caf-9381-2ff3de5b1ad6" width="300">|

## Ref
- With [NowInAndroid](https://github.com/android/nowinandroid) , the Snackbar, which never disappears, was always displayed to show that you were offline.

<img src="https://github.com/user-attachments/assets/f0838193-9cc5-4305-8241-c266030f08cb" width="300">

**Comment by takahirom** [comment]
I agree. How about creating a mapping for UnknownHostException and leaving other cases as they are?

**Comment by kosenda** [comment]
I think it was good!

**Comment by kosenda** [comment]
@takahirom 
Sorry 🙇 
 I didn't understand myself here, and I thought it was an addition to the following, but what are you assuming?

https://github.com/DroidKaigi/conference-app-2024/blob/2ff90401598a6fec38fa194b573f62b5a886a78a/core/model/src/commonMain/kotlin/io/github/droidkaigi/confsched/model/AppError.kt#L3-L20

→ add `public class UnknownHostException(message: String?, cause: Throwable?) : AppError(message, cause)`


https://github.com/DroidKaigi/conference-app-2024/blob/349693434b1e8ec005ecd37775fd109330e7616c/core/data/src/commonMain/kotlin/io/github/droidkaigi/confsched/data/NetworkService.kt#L25-L40

-> add
```kotlin
    if (this.toString().startsWith("java.net.UnknownHostException")) return UnknownHostException(
        message = "Connection failed, Check your connection.",
        cause = this
    )

```

**Comment by takahirom** [comment]
@kosenda 
How about adding a expect function like this?

expect fun knownPlatformExceptionOrNulll(e: Exception): AppError?

actual fun knownPlatformExceptionOrNulll(e: Exception): AppError? {
  if(e is UnknownHostException) {
    return AppError.InternetConnectionException(e)
  }
  return null
}

**Comment by kosenda** [comment]
That makes sense！
Continued, I'd like to work this🖐️
