### ISSUE TITLE
Displayed screen and selected MainScreenTab may be different when OS back gesture

### ISSUE THREAD

**Issue by kosenda** [DroidKaigi/conference-app-2024#411]
## Overview
As the title says, for example, if you perform the OS back gesture from EventMapScreen, you will transition to TimbetableScreen, but the tab below will remain in EventMapScreen.

https://github.com/user-attachments/assets/51f63783-e7ee-465f-b53a-2a3f644ee108

**Comment by hiesiea** [comment]
I'd like to try this issue 🙋

**Comment by takahirom** [comment]
Thanks! Assigned 👍
