### ISSUE TITLE
ProfileCard: validate nickname, occupation, link, and image

### ISSUE THREAD

**Issue by mikanIchinose** [DroidKaigi/conference-app-2024#418]
## Background
Previously, only a nickname was a required field, but the specifications have been changed so that occupation, link, and image are now also mandatory.

## Spec
- data: change all properties of ProfileCard to non-null
  - https://github.com/DroidKaigi/conference-app-2024/blob/e877e6d649365d871a41911b64ba892583cfca50/core/model/src/commonMain/kotlin/io/github/droidkaigi/confsched/model/ProfileCard.kt#L8-L14
  - https://github.com/DroidKaigi/conference-app-2024/blob/e877e6d649365d871a41911b64ba892583cfca50/core/data/src/commonMain/kotlin/io/github/droidkaigi/confsched/data/profilecard/ProfileCardJson.kt#L8-L14
- ui: change field required
  - occupation
  - link
  - image
- ui: validate form
  - nickname
  - occupation
  - link
  - image

error state
<img height=700 src="https://github.com/user-attachments/assets/eb70f469-ef1d-41bb-984f-88eef6936c42">

**Comment by yjyoon-dev** [comment]
I would like to try it! 🙋‍♂️

**Comment by Corvus400** [comment]
I've finished other tasks, so I'd like to start working on this one. 🙋

**Comment by mikanIchinose** [comment]
Thak you. I assigned.
