### ISSUE TITLE
Favorite feature is not supported correctly on iOS version

### ISSUE THREAD

**Issue by Aniokrait** [DroidKaigi/conference-app-2024#420]
# Overview
Favorite icons on the TimetableScreen doesn't work on iOS version app.
Even if you put the button, the session item wouldn't be added to the favorite list.

DetailScreen's button also doesn't perform properly.
In contrast to the TimetableScreen, the icon display changes correctly, although the favorite list never updates.

**Comment by Aniokrait** [comment]
And I will try to fix it.

**Comment by shin-usu** [comment]
Thank you for creating issue, but actually this issue is already fixed and created pull request.
It is reviewed now.

**Comment by Aniokrait** [comment]
@shin-usu 
Sorry to bother you.
I'll close this issue.
