### ISSUE TITLE
ProfileCard: Apply card screen design roughly

### ISSUE THREAD

**Issue by mikanIchinose** [DroidKaigi/conference-app-2024#421]
current
<img height=700 src="https://github.com/user-attachments/assets/7ba4293c-7c7c-4f9e-911d-fde58530d28f">

ideal
![スクリーンショット 2024-08-14 18 43 59](https://github.com/user-attachments/assets/08dbfe82-486b-46cb-b3a7-9ec4d0814ae6)
https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI?node-id=54953-64732&t=RETzg5ZvPOOUBJBF-4

**Comment by ked4ma** [comment]
i'll try it :raised_back_of_hand:

**Comment by mikanIchinose** [comment]
FYI

We are currently having difficulty exporting the card background image, so we have asked the designer to make it easier to export.

<img height=300 src="https://github.com/user-attachments/assets/2973a19f-bf8c-401f-8f4d-4d8caf4b7846">
<img height=300 src="https://github.com/user-attachments/assets/507c7431-5895-4bbf-a565-c54f68d05ec2">

**Comment by ked4ma** [comment]
I have a question 🙏 
How should I implement if the user doesn't set a profile image?
Is there any image for default? (Or no need to display?)

**Comment by mikanIchinose** [comment]
The specification has been changed to require a image to always be set.

link
https://github.com/DroidKaigi/conference-app-2024/issues/418

**Comment by ked4ma** [comment]
Got it! Thank you! 🙏

**Comment by mikanIchinose** [comment]
@ked4ma 
The designer made it easier to export. Here you go!

<img width=500 src="https://github.com/user-attachments/assets/1b0fa254-8204-40d7-b651-d592b4edf1d3">

https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI?node-id=57517-34333&t=aFwblG3l6MDmAuFL-4
