### ISSUE TITLE
ProfileCard: Add share feature

### ISSUE THREAD

**Issue by mikanIchinose** [DroidKaigi/conference-app-2024#422]
## Spec

1. click share button
2. create image to share
3. open Sharesheet

## Blocking
The design hasn't been created yet.

**Comment by takahirom** [comment]
We don't have time to implement fully, so I think we can start by sharing the front side of the card.
![image](https://github.com/user-attachments/assets/e0a4b35a-3b83-4453-bbd4-7e4d6cc94423)

**Comment by Corvus400** [comment]
I would like to try this issue. 🙋‍♂️

**Comment by mikanIchinose** [comment]
Thanks. Assigned!

**Comment by Corvus400** [comment]
@takahirom @mikanIchinose 
I thought it might be beneficial to include text using the information from ProfileCard when sharing. What are your thoughts on this?

```kotlin
data class Exists(
        val nickname: String,
        val occupation: String,
        val link: String,
        val image: String,
        val cardType: ProfileCardType,
    )
```

If you have any suggestions for the text, I would greatly appreciate them.

**Comment by Corvus400** [comment]
The image already contains text using this information, so it might be unnecessary, but...

**Comment by Corvus400** [comment]
@takahirom @mikanIchinose 
Please let me confirm one more point. ✋ 
When I press the share button, do I only need to share the visible side of the FlipCard? 🤔 
Or do I need to share both the front and back sides? 🤔

**Comment by takahirom** [comment]
I think it is better than nothing. So I think it is ok to share visible side.

**Comment by takahirom** [comment]
But the design has been finalized, and we may need to create an additional screen for rendering or implement a workaround for this issue.
https://github.com/DroidKaigi/conference-app-2024/issues/647

**Comment by takahirom** [comment]
We need to release version 1.0 anyway this week. If we don't have the share feature in version 1.0, we need to remove the share button from the app.

**Comment by takahirom** [comment]
I think it might be a small implementation and it is good 👍

**Comment by Corvus400** [comment]
@takahirom 
Thank you for your patience. 🙇 
The sharing function has been implemented. 🫡
