### ISSUE TITLE
In TimetableScreen, timetableUiType button is different from Figma

### ISSUE THREAD

**Issue by kosenda** [DroidKaigi/conference-app-2024#425]
## Overview
Same as the title, the icon seems to be different from Figma

|desc|Figma|Actual|
|---|---|---|
|Same|<img src="https://github.com/user-attachments/assets/6f43ac36-5a0e-4c93-a87b-f6f549c14eae" width="300">|<img src="https://github.com/user-attachments/assets/26403c23-5e99-424b-87b2-d3efc2fdd9c7" width="300">|
|Different|<img src="https://github.com/user-attachments/assets/05dbec44-6351-43ab-89e7-5b6f0098426f" width="300">|<img src="https://github.com/user-attachments/assets/f1de8217-e908-4fa7-91dc-a8c118b64132" width="300">|

Here are the areas that may need to be changed
https://github.com/DroidKaigi/conference-app-2024/blob/e877e6d649365d871a41911b64ba892583cfca50/feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/TimetableScreen.kt#L165-L175

**Comment by takahirom** [comment]
Thanks! Assigned 👍

**Comment by yumayuma708** [comment]
With the recent changes, I’ve managed to get very close to the ideal design in Figma. 
However, there’s still room for improvement in making the icon slightly more rounded.
To achieve this, I would need to download an SVG file.
 I’d like your opinion on whether I should go ahead with this implementation.

implementation | Figma
--- | ---
<img width="250" alt="スクリーンショット 2024-08-15 14 14 24のコピー" src="https://github.com/user-attachments/assets/c66bf236-cf7c-487c-9f78-99d8f7f81acb">| <img width="250" alt="スクリーンショット 2024-08-15 14 16 05" src="https://github.com/user-attachments/assets/c3b944ba-d715-4cbf-bbef-7a9e872eb50b">

**Comment by takahirom** [comment]
How about Icons.Rounded.ViewTimeline?

**Comment by yumayuma708** [comment]
Thank you for your comment.
Rounded.ViewTimeline and ideal icon are like these.

Rounded.ViewTimeline | Figma
--- | ---
<img width="100" alt="スクリーンショット 2024-08-15 18 31 37" src="https://github.com/user-attachments/assets/9c196fdd-7fea-4a5d-a0c6-607789b9d62b"> | <img width="100" alt="スクリーンショット 2024-08-15 14 16 05" src="https://github.com/user-attachments/assets/8909c568-5426-4090-8190-f21b8092f7ff">
[Material icon](https://fonts.google.com/icons?icon.query=view+timeline&icon.size=24&icon.color=%23e8eaed&icon.style=Rounded&icon.set=Material+Icons) | [Material symbol](https://fonts.google.com/icons?icon.query=view+timeline&icon.size=24&icon.color=%23e8eaed&icon.style=Rounded&icon.set=Material+Symbols)

Icons.Rounded.ViewTimeline is different from Figma design.

**Comment by takahirom** [comment]
Thank you for informing me. I'm comfortable with either option (Default.ViewTimeline or the downloaded SVG). However, I believe the downloaded SVG is preferable.

**Comment by yumayuma708** [comment]
OK! I'll try it.
