### ISSUE TITLE
[iOS] Set App Icon

### ISSUE THREAD

**Issue by ry-itto** [DroidKaigi/conference-app-2024#426]
Currently, the iOS app does not have an app icon set. Please set an app icon.

[App Icon Data](https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI?node-id=55884-8093&t=q2zRfKafYwjrnthM-4)

**Comment by yuheikawakami** [comment]
🙋
