### ISSUE TITLE
[iOS] There aren't event message on EventMap screen

### ISSUE THREAD

**Issue by shin-usu** [DroidKaigi/conference-app-2024#427]
## Overview
There aren't event message on EventMap screen.
<img src="https://github.com/user-attachments/assets/64367489-df6c-40f8-b2a1-ccdd6d8fb7dc" width=300 />

## Link
https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI?node-id=55725-8925&t=vHM8e2zFFMnGFcvn-4

**Comment by yuheikawakami** [comment]
🙋

**Comment by shin-usu** [comment]
Thank you😄 Assigned.
