### ISSUE TITLE
[iOS] Setup SwiftLint rules

### ISSUE THREAD

**Issue by ry-itto** [DroidKaigi/conference-app-2024#435]
Defines appropriate SwiftLint rules for this project.

**Comment by KaitoMuraoka** [comment]
🙋 
Is there a problem with [the same rules as in 2023](https://github.com/DroidKaigi/conference-app-2023/blob/main/app-ios/.swiftlint.yml)?
Any rules you would like to see added?

**Comment by ry-itto** [comment]
@KaitoMuraoka 
it's okey!
Thanks! Assigned 👍🏼
