### ISSUE TITLE
[iOS] Favorite Feature: Remove `Workshop Day` tab

### ISSUE THREAD

**Issue by MrSmart00** [DroidKaigi/conference-app-2024#441]
## Overview

`Workshop Day tab (9/11)` is no longer necessary. please you would remove the tab.

<img width="403" src="https://github.com/user-attachments/assets/cf2cfda7-74dd-403a-9a71-1841d31b6389">

## Goal

<img width="403" src="https://github.com/user-attachments/assets/e7fa7321-16bf-437e-b7b4-2dac5dfed4fb">

**Comment by aqua-ix** [comment]
I would like to try this task.

**Comment by aqua-ix** [comment]
I would like to try this task.
