### ISSUE TITLE
[iOS] SearchView Category Chip Data is missing

### ISSUE THREAD

**Issue by ry-itto** [DroidKaigi/conference-app-2024#442]
Currently, the iOS search screen does not have any category options. Please update it so that you can select category options.

**Comment by fumiyasac** [comment]
🙋‍♂️

**Comment by shin-usu** [comment]
@fumiyasac 
Thank you!! Assigned👍🏻

**Comment by fumiyasac** [comment]
@shin-usu I have a question about Model about TimetableCategory.
It seems that `Model.TimetableCategory.swift` generated from SKIE don't exist.
Please check and generate model file 🙏 
（※Probably, but I thought it would be necessary to modify the common logic.）

## Compare with TimetableCategory and Others

I checked Xcode project definitions within method jump.

__【DroidKaigi2024Day / TimetableSessionType / Lang】__

※ screen shot show TimetableSessionType model example.

When you execute method jump, you will show `Model.TimetableSessionType.swift`

![スクリーンショット 2024-08-19 4 46 08](https://github.com/user-attachments/assets/4b0bcc86-bb84-4096-86da-ada31d51b649)

![スクリーンショット 2024-08-19 4 46 28](https://github.com/user-attachments/assets/a92b285f-cb69-415b-ad7c-3daac38f54e6)

__【TimetableCategory】__

When you execute method jump, you will show `SharedTimetableCategory` written in Objective-C Header.

![スクリーンショット 2024-08-19 4 40 49](https://github.com/user-attachments/assets/3d7d12ce-d416-4114-9dbb-fcf189478bfd)

**Comment by shin-usu** [comment]
@fumiyasac 
Hmm...
I can find TimetableCategory model in shared package. Also, can find TimetableCategory definition in KMP, too.

<img width="599" alt="スクリーンショット 2024-08-19 16 31 42" src="https://github.com/user-attachments/assets/ad15db6c-9933-4a0d-af28-e03fe864e578">
<img width="446" alt="スクリーンショット 2024-08-19 16 32 17" src="https://github.com/user-attachments/assets/c02ee387-8e05-4b78-b039-529ed067e3bf">

If you absolutely cannot find the definition, you may find the contents by referring to TimetableCategory.kt.

**Comment by fumiyasac** [comment]
@shin-usu 

There is certainly a Model definition in the Android package.

![スクリーンショット 2024-08-19 18 01 26](https://github.com/user-attachments/assets/7a630be5-f603-44b4-a8df-e219933bb353)

What I would like to tell you is that the problem is that the TimetableCategory Model is not compatible with the Selectable protocol (that is, the automatically generated file in SKIE does not exist).

![スクリーンショット 2024-08-19 18 00 56](https://github.com/user-attachments/assets/8d575373-6db0-44b2-bd9d-312b337c9c0a)

Unfortunately, I don't know how to modify the common logic part.

**Comment by shin-usu** [comment]
@fumiyasac 
ちょっと認識齟齬ないように日本語で会話させてください 🙇🏻 

> the automatically generated file in SKIE does not exist

まずはSkieによる自動生成に関してお話ししますね。
自分の手元だとTimetableCategoryもSkieによってコードが自動生成されていることを確認できたので、共通ロジック部分への修正は不要だと思っています。
enum classであるTimetableSessionTypeと違い、TimetableCategoryはdata classであるため生成方法が異なっているということにご注意ください⚠️ 
もし全く定義に辿り着けない場合は、sharedパッケージの中にjumpしていただき、"TimetableCategory"で検索してみてもらえると、先ほど添付した画像の定義が見つかるかと思います。

**Comment by shin-usu** [comment]
次にどう実装するかについてですが、enumであればallCasesを渡せばいいところが、TimetableCategoryはenumではないため少し工夫が必要そうです。
Timetableクラスの定義を見るとcategoriesというTimetableCategoryの配列を持っているため、これをフィルタ候補として表示してあげると良さそうでした。(Android側もこのような実装になっていました)
<img width="507" alt="スクリーンショット 2024-08-19 18 52 02" src="https://github.com/user-attachments/assets/8eaa75a2-695a-4fc4-9919-cd64a6fa6803">

**Comment by fumiyasac** [comment]
@shin-usu  ご丁寧に説明ありがとうございます！（自分もきちんと理解ができておらずお手数をおかけしました :bow:）
頂きましたヒントを元に実装を進めてみます。
