### ISSUE TITLE
[iOS] Search Feature: Remove filter of `Workshop Day`

### ISSUE THREAD

**Issue by MrSmart00** [DroidKaigi/conference-app-2024#443]
## Overview

Workshop Day (9/11) is no longer necessary. please you would remove selection Item on the search filter.

<img width="406" alt="スクリーンショット 2024-08-14 22 37 26" src="https://github.com/user-attachments/assets/40b3ba68-9b88-422d-b183-9eaacc660448">

**Comment by hicka04** [comment]
🙋

**Comment by shin-usu** [comment]
@hicka04 
Thank you! Assigned👍
