### ISSUE TITLE
[iOS] About Feature: Update layout with Figma

### ISSUE THREAD

**Issue by MrSmart00** [DroidKaigi/conference-app-2024#444]
## Overview

About feature's layout is not current design. you would update it.

<img width=400 src='https://github.com/user-attachments/assets/967fb7f6-6c09-4972-a9cc-365d2dd85d0a' />

## Goal

<img width=400 src='https://github.com/user-attachments/assets/4965350e-a14e-46cf-be25-03cfb27711c6' />

**Comment by matsuurayuki1219** [comment]
🙋‍♂🙋‍♂

**Comment by ry-itto** [comment]
@matsuurayuki1219 

Thank you for your interest.
Sorry, the current "About" screen layout seems to be Goal's, so please check other issues 🙇🏼
