### ISSUE TITLE
[iOS] Timetable view title

### ISSUE THREAD

**Issue by charles-b-stb** [DroidKaigi/conference-app-2024#447]
Title is currently in English only. It should be both in English and Japanese depending on language setting.

Current | Should Be
:--: | :--:
<img width="300" src="https://github.com/user-attachments/assets/4df3fbe0-0ea2-4f3f-aaf2-2a21d919cb9c"> | <img width="300" src="https://github.com/user-attachments/assets/f633c1c0-5396-406c-840b-461c47e1ab8f">

**Comment by gibachan** [comment]
🙋

**Comment by shin-usu** [comment]
Thank you! Assigned👍
