### ISSUE TITLE
[Android] Timetable view title

### ISSUE THREAD

**Issue by charles-b-stb** [DroidKaigi/conference-app-2024#449]
Title is currently in English only. It should be both in English and Japanese depending on language setting.

Current | Should Be
:--: | :--:
<img width="300" src="https://github.com/user-attachments/assets/eb65eaa0-b8dc-464f-a8b5-f42f0b28f9a8"> | <img width="300" src="https://github.com/user-attachments/assets/f633c1c0-5396-406c-840b-461c47e1ab8f">

**Comment by chnotchy** [comment]
When I run the latest main branch on my local machine, the title is correctly displayed in Japanese according to the language setting.

<img src="https://github.com/user-attachments/assets/b622d865-9c7f-4b93-a40a-2abd0180b34d" width="300" />

**Comment by takahirom** [comment]
Thank you for your reporting. I'll close this issue. If there is a mistake, please let me know.
