### ISSUE TITLE
[iOS] Replace the grid/list switching icon

### ISSUE THREAD

**Issue by charles-b-stb** [DroidKaigi/conference-app-2024#450]
The icons for switching between Grid and List view on the timetable view should be changed to match the icons that were in the Figma design.

Current | Should Be
:--: | :--:
<img width="300" src=""> | <img width="300" src="">
<img width="300" alt="スクリーンショット 2024-08-14 23 52 30" src="https://github.com/user-attachments/assets/1eb05e07-fe26-455a-8b74-5d1e94837d7f"> | <img width="300" alt="スクリーンショット 2024-08-14 23 56 01" src="https://github.com/user-attachments/assets/4918212b-502b-455e-b64e-24e8ef969856">
<img width="300" alt="スクリーンショット 2024-08-14 23 52 37" src="https://github.com/user-attachments/assets/f79f25ed-fde3-4727-b6b7-9f940e037ccf"> | <img width="300" alt="スクリーンショット 2024-08-14 23 55 53" src="https://github.com/user-attachments/assets/8994bde0-f80f-429a-9343-014328d8538f">

**Comment by hicka04** [comment]
🙋

**Comment by shin-usu** [comment]
@hicka04 
Thank you!! Assigned👍🏻
