### ISSUE TITLE
[Android] Remove "Conference" text from selected tab

### ISSUE THREAD

**Issue by charles-b-stb** [DroidKaigi/conference-app-2024#451]
Currently when the day tab is selected in timetable view the selected tab says "Conference" above the selected date. This text is unnecessary and should be removed.

Current | Should Be
:--: | :--:
<img width="300" alt="スクリーンショット 2024-08-15 0 00 57" src="https://github.com/user-attachments/assets/8a6ca138-f39e-4517-a8f0-f5c03614ffdc"> | <img width="300" alt="スクリーンショット 2024-08-15 0 01 48" src="https://github.com/user-attachments/assets/42e2d92d-9a1c-478a-b1eb-e0946598bbe0">

**Comment by javaman97** [comment]
@charles-b-stb Can you _assign_ me this issue? I want to work on this issue .

**Comment by takahirom** [comment]
@javaman97 Thanks! Assigned 👍

**Comment by takahirom** [comment]
@javaman97 Could you take some time to resolve this? This is an important part of our application.

**Comment by javaman97** [comment]
![image](https://github.com/user-attachments/assets/fff7f590-1a0d-42b4-a5fb-dc84225962e4)

@takahirom  I was getting this error while cloning the project on Android Studio (Windows). I think it is related to MacOS.

**Comment by takahirom** [comment]
@javaman97 Could you please select the 'conference-app-2024: failed' item from the left panel and copy the error message? It's difficult to solve the problem without this information.

**Comment by javaman97** [comment]
> @javaman97 Could you take some time to resolve this? This is an important part of our application.

I have made the necessary changes and opened the PR. Please review the changes and let me know if there is any further changes required.
