### ISSUE TITLE
Align the UI of the Favorite/Empty screen with the Figma design proposal.

### ISSUE THREAD

**Issue by yumayuma708** [DroidKaigi/conference-app-2024#456]
## overview
Regarding the Favorite/Empty screen, the following two parts differ from the Figma design, so they need to be corrected.

1. The padding of the button at the top of the screen is different.
2. The line break in the text is different.

Figma | actual
--- | ---
<img width="357" alt="スクリーンショット 2024-08-14 22 45 23" src="https://github.com/user-attachments/assets/552797d4-7a8f-4625-9ffe-5268c3955b54">| <img width="357" alt="スクリーンショット 2024-08-15 1 20 48" src="https://github.com/user-attachments/assets/fdf0c4d5-242c-496f-b89e-2fead9463b0d">

**Comment by yumayuma708** [comment]
I want to try this issue 🙋‍♂️

**Comment by takahirom** [comment]
Thank you for finding this! Assigned 👍
