### ISSUE TITLE
Move FlipCard to component package

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2024#460]
I think this should be in component package.
https://github.com/DroidKaigi/conference-app-2024/blob/57da901c219a690b02525eef5e31a0d49b8ee504/feature/profilecard/src/commonMain/kotlin/io/github/droidkaigi/confsched/profilecard/FlipCard.kt#L40C14-L40C22

**Comment by Kei-1111** [comment]
I would like to work on this Issue.

**Comment by takahirom** [comment]
Thanks! Assigned 👍
