### ISSUE TITLE
Rename maxAboutHeaderOffsetDp to MaxAboutHeaderOffsetDp

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2024#462]
Super easy

https://github.com/DroidKaigi/conference-app-2024/blob/77ea7494cb8eb6cdde93726b25970c2ecc06210f/feature/about/src/commonMain/kotlin/io/github/droidkaigi/confsched/about/section/AboutDroidKaigiDetail.kt#L33

**Comment by soleil-colza** [comment]
Hi! Would like to work on this issue☺️

**Comment by takahirom** [comment]
I think you could handle more challenging tasks. 😄
Anyway, assigned. 👍

**Comment by soleil-colza** [comment]
> I think you could handle more challenging tasks. 😄
> Honoured to be said so though I was a bit afraid of picking up a harder task😅
I will regard this issue as a good warm-up and request working on harder ones afterwards!!

**Comment by soleil-colza** [comment]
@takahirom Deep apologies for mentioning you multiple times, looking into the issue it seems to be way easier than I thought.
I feel like it's better to let novices work on this as a first step, so if you feel the same way could you please unassign me from this?
It's totally up to you, thank you🙇🏻‍♀️

**Comment by takahirom** [comment]
Thank you for your cooperation in helping beginners! 🙏

**Comment by arcenjoyed** [comment]
I'm a beginner but I wanna give it a try! @takahirom

**Comment by honoka5** [comment]
Me too. I'm a beginner,but I want to try it! @takahirom

**Comment by honoka5** [comment]
I'm a beginner too,but I want to try it ! @takahirom

**Comment by honoka5** [comment]
I'm a beginner too,but I want to try it ! @takahirom

**Comment by takahirom** [comment]
Thanks! Assigned 👍
