### ISSUE TITLE
Make EventResponse's message nullable

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2024#465]
The server could return null for the message field, and I want to make sure that our app runs even if the server returns null.
https://github.com/DroidKaigi/conference-app-2024/blob/0c6dd2281c6502fa30c9b43efc7cd1205cff3664/core/data/src/commonMain/kotlin/io/github/droidkaigi/confsched/data/eventmap/response/EventResponse.kt#L9

**Comment by mannodermaus** [comment]
✋

**Comment by takahirom** [comment]
Thanks! Assigned 👍
