### ISSUE TITLE
Add a dashedRoundRect modifier extension function to the design system module

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2024#466]
I think we can have a shared function for this.

<img width="288" alt="image" src="https://github.com/user-attachments/assets/0428905a-ce5c-4375-9860-196c3ca67f31">

https://github.com/DroidKaigi/conference-app-2024/blob/0d6f6c4b2a8fe563172de41415a2952134278cb1/feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/component/TimetableItemDetailSummaryCard.kt#L79

https://github.com/DroidKaigi/conference-app-2024/blob/a14a7525f49107c46978164c74df108f2cdea4b1/feature/about/src/commonMain/kotlin/io/github/droidkaigi/confsched/about/component/AboutDroidKaigiDetailSummaryCard.kt#L46

**Comment by ked4ma** [comment]
:raised_hand_with_fingers_splayed:

**Comment by takahirom** [comment]
Thanks! Assigned 👍
