### ISSUE TITLE
Some screens have content visible in NavigationBar and some do not

### ISSUE THREAD

**Issue by kosenda** [DroidKaigi/conference-app-2024#471]
## Overview
TimetableScreen, FavoriteScreen, and AboutScreen are displayed but the following screens are not in NavigationBar.
- ContributorsScreen
- EventMapScreen
- SearchScreen
- SponsorsScreen
- StaffScreen

|visible(TimetableScreen)|invisible(StaffSceren)|
|---|---|
|<img src="https://github.com/user-attachments/assets/eddf0e78-751a-4c41-93c9-40b721203e23" width="300">|<img src="https://github.com/user-attachments/assets/56aaa542-25ed-458c-8a47-2cf83b32bc5a" width="300">|

## Might be helpful
- `.padding(padding)` → `.padding(top = innerPadding.calculateTopPadding())`  would seem to work.

## What's on my mind
- PaddingValues in Scaffold's content has both `padding` and `innerPadding` names

**Comment by takahirom** [comment]
Sorry, I don't understand which part you're referring to. Could you elaborate on the NavigationBar?

**Comment by kosenda** [comment]
Sorry for the confusing explanation 🙇
It is about the part in the red box !

<img width="500" alt="スクリーンショット 2024-08-15 22 07 57" src="https://github.com/user-attachments/assets/544db337-6cd8-4ece-a73d-a469a5fcee50">

**Comment by takahirom** [comment]
Oh I understand! Thanks.

**Comment by ked4ma** [comment]
Can I do this? :raised_hand_with_fingers_splayed:

**Comment by takahirom** [comment]
Thanks! Assigned 👍
