### ISSUE TITLE
Use app version from BuildConfigProvider

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2024#484]
We are currently using a constant for the app version on the about screen. Ideally, we should use the version from BuildConfigProvider. The challenge is how to inject it. We could refer to last year's app for guidance.

https://github.com/DroidKaigi/conference-app-2024/blob/edd88b0c94a6060e94b2b7427fa53fe25dcd9fe1/feature/about/src/commonMain/kotlin/io/github/droidkaigi/confsched/about/AboutScreen.kt#L127

**Comment by obaya884** [comment]
I would like to get this issue. 🙋‍♂️

**Comment by takahirom** [comment]
Thanks! Assigned 👍
