### ISSUE TITLE
FavoriteFilters in FavoriteScreen differ between Figma and actual display.

### ISSUE THREAD

**Issue by kosenda** [DroidKaigi/conference-app-2024#486]
## Overview
The following two points are likely to be different

- `FavoriteFilterChip` padding is narrower than Figma
- In Figma, the background color is always the same as that of TopAppBar, but the actual display is different.

|Figma|actual|
|---|---|
|<img src="https://github.com/user-attachments/assets/a5ae52be-e86a-4fef-b18e-9ccd134b0f4a" width="300">|<img src="https://github.com/user-attachments/assets/43cc4b73-6099-4b15-b1a9-9fa0f8e091dd" width="300">|

## Might be helpful for you
- As for padding, we don't set padding in `FavoriteFilterChip`, and I think we can fix it only by setting Modifier.

**Comment by syam4869** [comment]
I want to work on this issue!🙋‍♂️

**Comment by takahirom** [comment]
Thanks! Assigned 👍
