### ISSUE TITLE
Build fail on TimetableGridItem

### ISSUE THREAD

**Issue by Pluu** [DroidKaigi/conference-app-2024#488]
A build failure was found that appeared to be a side effect of the icon behavior added to timetable grid items.

The return type of the room icon does not match the required parameter type.
Using “vectorResource” does not resolve this issue as TimetableRoom#icon returns null.

The null issue appears to be caused by where the RoomIcon is converted to a “DrawableResource”. (RoomIconExt.kt)
I think this issue could be resolved by design or with guide from @takahirom.

<img width="1480" alt="b" src="https://github.com/user-attachments/assets/8651fd40-c7d5-42d6-8510-3657d60dc0c5">

**Comment by hiroaki404** [comment]
I think this issue is resolved by #491

**Comment by takahirom** [comment]
Thank you for fixing this @hiraike32  !
