### ISSUE TITLE
Improve ProfileCardEditScreen(use ProfileCardScreenTheme)

### ISSUE THREAD

**Issue by hiroaki404** [DroidKaigi/conference-app-2024#489]
We have additional task to do in EditScreen of ProfileCard.

- use ProfileCardScreenTheme

https://github.com/DroidKaigi/conference-app-2024/pull/459#discussion_r1718333277

**Comment by takahirom** [comment]
I think we can improve the naming of ProfileCardScreenTheme as well.

**Comment by ked4ma** [comment]
What do you think if change the namings as like followings?
- ProfileCardTheme -> CardType
- ProfileCardScreenTheme -> ProfileCardTheme

I aimed not to use "theme" twice.

**Comment by takahirom** [comment]
Looks great!

**Comment by takahirom** [comment]
Let me assign you!
