### ISSUE TITLE
In SearchScreen, if there is no filter, it seems correct that there are no search results

### ISSUE THREAD

**Issue by kosenda** [DroidKaigi/conference-app-2024#496]
## Overview
It seems correct from Figma that when no filter is set in SearchScreen, nothing is shown in the search results.
（In 2023, it all showed up when you transitioned to the search screen.）

<img width="600" alt="image" src="https://github.com/user-attachments/assets/1acf8a30-7a1b-402d-adf2-d7e922dde994">

## Actual
https://github.com/user-attachments/assets/75fce3ee-c47e-4f33-8c74-57b4be536cbc

## Figma
https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI?node-id=54953-72675&t=g8UpEUZMcVhWzs6z-4

**Comment by takahirom** [comment]
@nobonobopurin 
I think the current app state is good. But if you have any opinion on the empty screen when we open the search page. Please let me know.

**Comment by nobonobopurin** [comment]
@kosenda  @takahirom It is correct that nothing will appear in the search results unless you set a filter. However, if no text is entered in the text field and only a filter is set, we would like the specification to display a list in the search results.
![Uploading スクリーンショット 2024-08-18 19.08.04.png…]()

**Comment by ked4ma** [comment]
- all filters are not set and search text is empty -> nothing to show
- some filters are set or search text is not empty -> show search result
- filter conditions are not empty and filter result is empty -> show empty message

is my recognition correct?
if ok, I'll do it! :raised_back_of_hand:
