### ISSUE TITLE
(Suggestion) Enable to select the text of DescriptionSection in TimetableItemDetailScreen.

### ISSUE THREAD

**Issue by kosenda** [DroidKaigi/conference-app-2024#498]
## Overview
In the 2023 app, it was selectable, so I was hoping this year's app could copy it as well...!

[conference-app-2023](https://github.com/DroidKaigi/conference-app-2023)

https://github.com/user-attachments/assets/c4e058e2-8eda-485b-ac8f-08ec0d5e3d0b

**Comment by o-ats-o** [comment]
I want to try this issue 🙋‍♂️

**Comment by takahirom** [comment]
@kosenda Thank you for creating many issues. It is essential for us.
@o-ats-o Thanks! Assigned 👍
