### ISSUE TITLE
Scroll to current time session when opening the timetable

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2024#509]
I think it would be convenient if we could see the session that's currently in progress.
If we could have a test implementation as well, it would be great.

**Comment by yjyoon-dev** [comment]
🙋

**Comment by takahirom** [comment]
Thanks! Assigned 👍

**Comment by takahirom** [comment]
Unfortunately, @yjyoon-dev became busy. So I unassigned @yjyoon-dev. But the the implementation is almost finished. 

Now, I'm waiting for you guys to raise your hands for this issue. 🙋

**Comment by hiroaki404** [comment]
I try this✋

**Comment by raseln** [comment]
I want to try this 🤚

**Comment by takahirom** [comment]
First come, first served, so I'll assign hiroaki404. Thank you for raising your hand for this.
