### ISSUE TITLE
In TimetableItemDetailScreen, DescriptionText is not in Expand state when Favorite button is pressed and returns to FavoriteScreen.

### ISSUE THREAD

**Issue by kosenda** [DroidKaigi/conference-app-2024#510]
## Overview
If you don't need it, please close it 🙇

When the DescriptionText is in the Expand state on the TimetableItemDetailScreen and the Favorite button is pressed to return to the FavoriteScreen, the DescriptionText is not in the Expand state.
Personally, I think it would be desirable for the Expand state to remain the same before transition.

https://github.com/user-attachments/assets/dac4444c-2981-4a9c-a110-c065ba844d29

**Comment by ked4ma** [comment]
:raised_back_of_hand:
