### ISSUE TITLE
DescriptionSection of TimetableItemDetailScreen shows the More button even when there is no description

### ISSUE THREAD

**Issue by kosenda** [DroidKaigi/conference-app-2024#511]
## Overview
The DescriptionSection of the TimetableItemDetailScreen shows the More button even if there is no description at all.
Personally, I thought it would be better to display the More button if there are more than 7 characters, as specified by `maxLines = if (isExpand) Int.MAX_VALUE else 7` .

https://github.com/user-attachments/assets/cb3da091-3c4a-49c5-904d-e912743cdc47

**Comment by shxun6934** [comment]
I try this issue ! 🙋‍♂️

**Comment by takahirom** [comment]
Thanks! Assigned 👍
