### ISSUE TITLE
Scroll is not possible when Favorite is Empty in FavoriteScreen.

### ISSUE THREAD

**Issue by kosenda** [DroidKaigi/conference-app-2024#517]
## Overview
When Favorite is Empty on a FavoriteScreen, it indicates that there are no favorites, but not all of the content may be displayed because it is not a Scrollable screen.

example: Pixel6 + DisplaySize max + FontSize max + splitScreen
<img src="https://github.com/user-attachments/assets/718a973b-0679-460c-8cf5-6dbf9e2155cd" width="350">

## Might be helpful
I think we can fix it by simply setting Scrollable here

https://github.com/DroidKaigi/conference-app-2024/blob/a1a0fdc8d53d1bb078644e4a0ae661feecf9b08f/feature/favorites/src/commonMain/kotlin/io/github/droidkaigi/confsched/favorites/section/FavoriteSheet.kt#L104-L142

**Comment by honoka5** [comment]
I'm a beginner , but I want to try it !

**Comment by honoka5** [comment]
I'm a beginner ,but I want to try it ! @takahirom

**Comment by takahirom** [comment]
Thanks again! Assigned 👍
