### ISSUE TITLE
It might be better to have imePadding on SearchScreen.

### ISSUE THREAD

**Issue by kosenda** [DroidKaigi/conference-app-2024#519]
## Overview
The trailing item is hidden when the keyboard is out in SearchScreen, so I thought it would be better to add imePadding

actual

https://github.com/user-attachments/assets/eb9c6f75-8e89-434d-ac26-dace7ff6eac5

**Comment by rand16** [comment]
I'm a beginner, but I would like to take this issue!

**Comment by takahirom** [comment]
Thanks, Assigned 👍 I'm looking for your contribution!
