### ISSUE TITLE
Search Feature: focus on search bar when transitioning search screen

### ISSUE THREAD

**Issue by shin-usu** [DroidKaigi/conference-app-2024#525]
## Overview
Currently, when user transition to search screen, search bar is not focused on.
But users transition because of searching sessions, so it is better for the UX to be focused on the search bar from the beginning.

## Image
When transitioning to search screen...
| As Is | To Be |
| ---- | ---- |
| <img src="https://github.com/user-attachments/assets/7af97831-60d6-4e5b-8bd8-76e65c44092e" width=300 /> | <img src="https://github.com/user-attachments/assets/f76341ea-cc04-4be3-a0f7-807791389247" width=300 /> |

**Comment by nyagasan** [comment]
🙋

**Comment by shin-usu** [comment]
@nyagasan 
Thank you!! Assigned 👍🏻
