### ISSUE TITLE
Use AnimatedLargeTopAppBar for Contributor and Sponsor Screens

### ISSUE THREAD

**Issue by r-kuno-zer0** [DroidKaigi/conference-app-2024#528]
Currently, the Contributor and Sponsor screens do not use the [AnimatedLargeTopAppBar](https://github.com/DroidKaigi/conference-app-2024/blob/16d2480e1ede9850b4ea5d3c803763187cd3b8d9/core/ui/src/commonMain/kotlin/io/github/droidkaigi/confsched/ui/component/AnimatedLargeTopAppBar.kt#L3) component. However, [the Staff screen already implements this component](https://github.com/DroidKaigi/conference-app-2024/blob/main/feature/staff/src/commonMain/kotlin/io/github/droidkaigi/confsched/staff/StaffScreen.kt#L110C17-L110C39). 

The Figma design for the Staff Screen correctly uses the AnimatedLargeTopAppBar, so I think we should update the Contributor and Sponsor screens to follow this design.

 Current |  Figma
:--: | :--:
<img src="https://github.com/user-attachments/assets/9fd799d1-414d-407c-b91a-6b6b09414d71" width="300" /> | <img src="https://github.com/user-attachments/assets/ea8608b5-405a-4855-b7f3-3cdd41e20c3d" width="300" />
<img src="https://github.com/user-attachments/assets/68f43d49-2bc1-4456-8a93-2ee539a43cb5" width="300" /> | <img src="https://github.com/user-attachments/assets/209046fe-5235-4390-bed5-b1fc6611cd5e" width="300" />
<img src="" width="300" /> | <img src="" width="300" />

**Comment by r-kuno-zer0** [comment]
If there are no problems, I would like to try this issue🙋‍♂️

**Comment by takahirom** [comment]
Thanks! Assigned 👍
