### ISSUE TITLE
Add a line to TimetableGrid to indicate the current session

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2024#537]
Could we implement a feature to display the current time session?
It would be beneficial to have a screenshot test or preview for this feature.
https://github.com/DroidKaigi/conference-app-2024/blob/main/feature/sessions/src/androidUnitTest/kotlin/io/github/droidkaigi/confsched/sessions/TimetableScreenTest.kt

**Comment by kitakkun** [comment]
I'd like to take on this issue. ✋🏻 It may take some time though.

**Comment by takahirom** [comment]
Thanks! Assgined
