### ISSUE TITLE
Add a test that ensures "if the description is lengthy, it should display a More button" to TimetableDetailScreenTest

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2024#539]
https://github.com/DroidKaigi/conference-app-2024/blob/main/feature/sessions/src/androidUnitTest/kotlin/io/github/droidkaigi/confsched/sessions/TimetableItemDetailScreenTest.kt

**Comment by dao0203** [comment]
I would like to work on  this issue :raising_hand:

**Comment by takahirom** [comment]
Thanks! Assgined
