### ISSUE TITLE
✖️ button for search input is always visible in Figma.

### ISSUE THREAD

**Issue by kosenda** [DroidKaigi/conference-app-2024#541]
## Overview
As the title says, it seems correct to show the x button even when there is no input on the search screen...

|Figma|actual|
|---|---|
|<img src="https://github.com/user-attachments/assets/f9684696-2c2e-402c-8391-1c8bbbb36ff9" width="300">|<img src="https://github.com/user-attachments/assets/c5f08573-f91a-46b9-b130-e014c66e9eea" width="300">|

## Figma
https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI?node-id=54953-72675&t=wePCfOpSn8KIgCjN-4

**Comment by nobonobopurin** [comment]
@kosenda Sorry about that. I missed removing the ✖️ button in the design. The Figma file is updated now.

**Comment by takahirom** [comment]
Thanks! We can close this issue now!
