### ISSUE TITLE
Maybe the OssLicense screen should be in dark mode only

### ISSUE THREAD

**Issue by kosenda** [DroidKaigi/conference-app-2024#542]
## Overview
Currently, the dark and light modes have changed depending on the OS environment in OssLicense, but I thought it would not be good for the app to suddenly have a white light screen in terms of its design.

https://github.com/user-attachments/assets/a9d8bca7-0a30-4f79-910b-50d83877783f

**Comment by kuwabara-hirokazu** [comment]
I would like to take on the challenge.
