### ISSUE TITLE
Design differences in EventMapScreen's Tab should be corrected.

### ISSUE THREAD

**Issue by Corvus400** [DroidKaigi/conference-app-2024#546]
As the title suggests, the display is not currently designed to change depending on 1F/B1F.
This feature would need to be implemented as it was last year.

**Comment by Corvus400** [comment]
At any rate, I would like to work on this on my end, as basic functionality should be implemented as quickly as possible. :hand:

**Comment by Corvus400** [comment]
@takahirom 
I have a question. 🙋‍♂️
Looking at the JSON shown in [this Issud](https://github.com/DroidKaigi/conference-app-2024/issues/258), is it unnecessary to filter the EventMap depending on FloorLevel this year? 🤔 
I will try to address this as an Issue to fix the Tab design differences for once. 💪

**Comment by Corvus400** [comment]
The issue of the Description not being displayed will be addressed in another Issue, so I will not touch that one.
https://github.com/DroidKaigi/conference-app-2024/issues/579

**Comment by takahirom** [comment]
> the display is not currently designed to change depending on 1F/B1F.

Is 'the display' referring to how we filter the events or not?
Well, we could have events outside the rooms. So I don't think we need to filter the events.

@mhidaka Thank you for handling the event maps. Do you have any opinions about this?

**Comment by mhidaka** [comment]
Thank you for your suggestion and contrib!

This year's DroidKaigi has no plans to hold any events on the 1st floor. Therefore, We think it would be more convenient to display all events in both cases, whether the map is displayed on the 1st floor or the B1 floor.

**Comment by takahirom** [comment]
Thank you for your insight! Let's close this issue. I appreciate your suggestion.
