### ISSUE TITLE
Introduction of ThemedIcon that appears to have two colors

### ISSUE THREAD

**Issue by kosenda** [DroidKaigi/conference-app-2024#553]
## Overview
ThemedIcon is not applied, but I feel it should be.
Also, if we introduced ThemedIcon as usual, it would look quite similar to the 2022 and 2023 app icons, so we thought it would be a good idea to do the following to differentiate them by making them look like they are composed of two different colors.
（Creating a monochrome will not affect the display of the splash icon at startup）

1. Introduce ThemedIcon as we did last year.
2. Create a file named `ic_launcher_monochrome.xml` with a copy of `ic_launcher_foreground.xml` in a directory named `drawable-v31`.
3. Set `ic_launcher_monochrome` on `monocrome` of `ic_launcher_round.xml` and `ic_launcher.xml`
4. Set `android:fillAlpha=“0.5”` in one of two paths of `ic_launcher_monochrome.xml` to make one side figure translucent

↓

|Before|After|
|---|---|
|<img src="https://github.com/user-attachments/assets/4b85647d-e6d4-4b7a-a44d-6537408fb4aa" width="300">|<img src="https://github.com/user-attachments/assets/bcc63974-54da-4da0-8569-7750af41fc13" width="300">|

## 2022, 2023, 2024 Comparison
From left to right: 2022, 2023, this year

<img src="https://github.com/user-attachments/assets/95e0bd20-2485-423c-a767-04ffa42a79d4" width="350">

**Comment by nobonobopurin** [comment]
@kosenda That sounds like a great idea! Introducing a ThemedIcon with two colors would add a nice touch. I’m on board with this!

**Comment by kosenda** [comment]
@nobonobopurin cc: @takahirom 
Thank you for your consideration!
Above samples are 50% alpha on the left and 100% alpha on the right,
What do you think?

**Comment by nobonobopurin** [comment]
@kosenda I think it looks good!✨

**Comment by takahirom** [comment]
Thanks! I unblocked this issue!

**Comment by kosenda** [comment]
@takahirom 
you might want to remove the assignment...🙇‍♂

**Comment by kosenda** [comment]
@takahirom 
Sorry to keep repeating!
I think it is difficult for contributors to raise their hands if they are assigned here...!

**Comment by takahirom** [comment]
I apologize. I have unassigned this issue. 🙇

**Comment by Corvus400** [comment]
I would like to work on this task. 🙋‍♂️

**Comment by takahirom** [comment]
Thanks!
