### ISSUE TITLE
Migrate describeBehaviors to RoboSpec Library

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2024#558]
There is an important difference between the Library and our implementation. The `run` method is renamed to `doIt`. This is because we could accidentally use the standard library's `run` method.
However, if we migrate it in one PR, it could cause many conflicts. So, how about adding a `run` extension function, deprecating it, and then applying it everywhere?
https://github.com/takahirom/robospec

**Comment by hiroaki404** [comment]
I try this ✋

**Comment by hiroaki404** [comment]
> So, how about adding a run extension function
Sorry I can't understand above.
I add member function.
