### ISSUE TITLE
Maybe it would be better to set the sharedElement in TimetableItemDetailScreen to TimetableItemDetailHeadline instead of Surface

### ISSUE THREAD

**Issue by kosenda** [DroidKaigi/conference-app-2024#561]
## Overview
Please CLOSE if we don't need it 🙇

In `TimetableItemDetailScreen`, `sharedElement` set to `Surface`, but I thought it would be better to set it to `TimetableItemDetailHeadline` which is just the items displayed in the `TimetableList`.
Personally, I feel that when set up on a Surface, the changes outside of the common areas are drastic.

The following is the actual `sharedElement` set for each ↓

|Animation speed|Surface|TimetableItemDetailHeadline|
|---|---|---|
|x1.0|<video src="https://github.com/user-attachments/assets/6fb4d7d7-2232-4512-91eb-f1cd8e381762">|<video src="https://github.com/user-attachments/assets/22da636c-b3d6-4244-90fc-e5dea077fd81">|
|x0.2|<video src="https://github.com/user-attachments/assets/9ea64cb9-7531-400a-bd52-c479c103ce1d">|<video src="https://github.com/user-attachments/assets/839d377a-9f4a-43ad-b8ba-60047028510f">|

## Location of the content of the PR above
https://github.com/DroidKaigi/conference-app-2024/blob/441a53ca4f0fd3e4181b88d29c5e19932d3c6164/feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/TimetableItemDetailScreen.kt#L200-L216

**Comment by takahirom** [comment]
In this case, the session item in the list does not represent the TimetableItemDetailHeadline. Therefore, the item's shared element transition target should be the detail screen. While the animation looks good if we use the Headline, I believe the transition's purpose is to guide the user to identify which elements are the same.

**Comment by kosenda** [comment]
I see... 
I was only aware of what was displayed. 🙇
I will CLOSE this PR.
