### ISSUE TITLE
Add SearchScreenTest for Category Filter

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2024#562]
Please add a test for the Category Filter.
It should be something like this: "when we filter tests with App Architecture - it should display App Architecture timetable items"

https://github.com/DroidKaigi/conference-app-2024/blob/3c08e519ed4eb673e902031398112facc30bb0dc/feature/sessions/src/androidUnitTest/kotlin/io/github/droidkaigi/confsched/sessions/SearchScreenTest.kt#L46

We can run the test by clicking the "Run" button on the left side of Android Studio.

<img width="144" alt="image" src="https://github.com/user-attachments/assets/c7b29374-cc0b-4f67-a667-b5cfd73a41bf">

**Comment by Corvus400** [comment]
I would like to work on this task. 🙋‍♂️
