### ISSUE TITLE
Add some TimetableScreenTest tests for 9/11, 9/12, 9/13 and switch Grid timetable

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2024#564]
The test would be like `when the current date is [day name] **and switch to grid timetable** it should show timetable items for [tabName]` 
https://github.com/DroidKaigi/conference-app-2024/blob/main/feature/sessions/src/androidUnitTest/kotlin/io/github/droidkaigi/confsched/sessions/TimetableScreenTest.kt#L140C31-L140C55

We can run the test by clicking the "Run" button on the left side of Android Studio.

<img width="144" alt="image" src="https://github.com/user-attachments/assets/c7b29374-cc0b-4f67-a667-b5cfd73a41bf">

**Comment by ked4ma** [comment]
:raised_hand_with_fingers_splayed:

**Comment by takahirom** [comment]
Thanks! Assigned 👍
