### ISSUE TITLE
The title is not translated correctly on the timetable detail screen.

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2024#566]
When we open the timetable detail, we should respect the session's language. However, if we choose a specific language from the top-right menu of the screen, we should see the content in that language. Currently, the title is always shown in the device's default language.
When we select a language on the timetable item detail screen, it should display the translated title of the session.

**Comment by SEKI-YUTA** [comment]
The specific solution is still unclear, but I would like to take on the challenge.
