### ISSUE TITLE
Background content can be manipulated during loading display when editing ProfileCardScreen.

### ISSUE THREAD

**Issue by kosenda** [DroidKaigi/conference-app-2024#567]
## Overview
As the title suggests, it may not be common for background content to be operable during loading of card creation timing.
However, even if the card is operated during loading, it will not be displayed or saved, so the impact will be quite minimal.

https://github.com/user-attachments/assets/26a69751-67a4-4a4e-a797-d662009745c8

**Comment by hicka04** [comment]
🙋

**Comment by takahirom** [comment]
Thanks! Assigned 👍

**Comment by takahirom** [comment]
https://github.com/DroidKaigi/conference-app-2024/pull/619#issuecomment-2295282026
