### ISSUE TITLE
The tint of the unselected icon on the bottom bar is darker than in the Figma design

### ISSUE THREAD

**Issue by Yamada-Ika** [DroidKaigi/conference-app-2024#574]
|  before  |  after  |
| ---- | ---- |
| <img width="300" alt="スクリーンショット 2024-08-17 23 46 39" src="https://github.com/user-attachments/assets/685ddd87-652a-4eef-90f2-026f8a03d90f"> | <img width="300" alt="スクリーンショット 2024-08-17 23 46 48" src="https://github.com/user-attachments/assets/6a417d79-2930-4f0c-859f-a4fe131c149d"> |

**Comment by kako351** [comment]
🙋‍♂️

**Comment by Yamada-Ika** [comment]
@kako351 Thanks! Assigned!
