### ISSUE TITLE
The color of the bottom bar on the timetable detail screen differs from the Figma design

### ISSUE THREAD

**Issue by Yamada-Ika** [DroidKaigi/conference-app-2024#575]
|  actual  |  expected  |
| ---- | ---- |
| <img width="300" alt="スクリーンショット 2024-08-17 23 56 21" src="https://github.com/user-attachments/assets/6b4666f7-0969-44b5-9191-729b5cb49f6c"> | <img width="300" alt="スクリーンショット 2024-08-17 23 56 31" src="https://github.com/user-attachments/assets/0b7c011f-c2da-4d8b-9e41-43183b578695"> |

**Comment by urotarou** [comment]
✋

**Comment by Yamada-Ika** [comment]
@urotarou  Thanks! Assigned!
