### ISSUE TITLE
Switch the translation based on the device's language settings when opening the timetable detail screen

### ISSUE THREAD

**Issue by Yamada-Ika** [DroidKaigi/conference-app-2024#576]
Currently, Japanese is displayed regardless of the device's language settings. It would be more convenient if, when English is set, the session descriptions and other elements are switched to English from the start. Additionally, for languages other than Japanese and English, it would be preferable if they are switched to English.

**Comment by mangano-ito** [comment]
:raising_hand:

**Comment by Yamada-Ika** [comment]
@mangano-ito Thanks! Assigned!

**Comment by Yamada-Ika** [comment]
A more useful feature has been proposed in https://github.com/DroidKaigi/conference-app-2024/issues/748, and a PR has already been merged.
Therefore, we will close this issue. Thank you.
