### ISSUE TITLE
ProfileCardScreen may cause layout corruption on devices that are long horizontally

### ISSUE THREAD

**Issue by kosenda** [DroidKaigi/conference-app-2024#583]
## Overview
The layout is broken when the device is turned horizontally on a small screen, split screen, or portrait device, and the content is partially hidden because it is not designed to be scrollable.
I think for the purpose and nature of profile cards, it is not as simple as just being able to scroll, but it is necessary to reduce the size of the profile card so that it fits on the profile card screen while maintaining the aspect ratio.

https://github.com/user-attachments/assets/d14a3301-5426-437e-a2eb-c3ea66715ba6

**Comment by s-kamada** [comment]
Hello, I'd like to try this! 🙋

**Comment by s-kamada** [comment]
@kosenda 
When I checked the behavior on the current latest branch, it scrolls when the screen height is not enough and the layout is not broken.
Can I therefore CLOSE this issue?

https://github.com/user-attachments/assets/0df425a7-ca33-4348-94b5-fed59f4f2e27

**Comment by kosenda** [comment]
@s-kamada 
Indeed! I'm not a Staff member so I honestly can't judge whether it should be closed or not, but I personally feel it maybe be closed...!

**Comment by s-kamada** [comment]
Oh! I see!
I thought you were a staple since you were active in various issues, my apologies!

@takahirom 
Could we close this issue?

**Comment by takahirom** [comment]
Thank you for considering and suggesting what we need to do!
