### ISSUE TITLE
Change the background color of the sponsor screen cards to white

### ISSUE THREAD

**Issue by Yamada-Ika** [DroidKaigi/conference-app-2024#589]
Currently, the background color is gray, but white would be preferable

<img width="300" alt="スクリーンショット 2024-08-18 10 09 22" src="https://github.com/user-attachments/assets/e0db4c6f-0e35-497a-8f9d-9737f6066e16">

**Comment by Kei-1111** [comment]
I would like to work on this issue.

**Comment by Yamada-Ika** [comment]
@Kei-1111 Thanks! Assigned!

**Comment by Yamada-Ika** [comment]
It seems that this issue has been fixed in https://github.com/DroidKaigi/conference-app-2024/pull/610.
I will close now.
