### ISSUE TITLE
Even when the device language is set to Japanese, the title on the sponsor screen does not switch to Japanese

### ISSUE THREAD

**Issue by Yamada-Ika** [DroidKaigi/conference-app-2024#590]
The text in the top app bar should be in Japanese, but it remains in English

<img width="300" alt="スクリーンショット 2024-08-18 10 13 06" src="https://github.com/user-attachments/assets/bd024fd6-7e1f-4d43-b9ab-de3d9b86848b">

**Comment by gargVader** [comment]
Let me pick this & #591 up as they are same

**Comment by Yamada-Ika** [comment]
@gargVader Thanks! Assigned!

**Comment by gargVader** [comment]
@Yamada-Ika PTAL whenever you can 
#687

**Comment by Yamada-Ika** [comment]
Thank you for your contribution!
Fixed in https://github.com/DroidKaigi/conference-app-2024/pull/687, so I'll close this.
