### ISSUE TITLE
When scrolling on the profile screen, the title does not match the Figma design

### ISSUE THREAD

**Issue by Yamada-Ika** [DroidKaigi/conference-app-2024#593]
It is expected that the text in the top app bar will move to the center when scrolling.

|  actual  |  expected  |
| ---- | ---- |
| <img width="300" alt="スクリーンショット 2024-08-18 10 31 26" src="https://github.com/user-attachments/assets/bddfd793-af48-46a3-a9de-0ed6c3cfe045"> | <img width="300" alt="スクリーンショット 2024-08-18 10 31 42" src="https://github.com/user-attachments/assets/783ef816-edeb-4e01-b019-8df3c2b23c4b"> |

**Comment by kota-shiokara** [comment]
🤚

**Comment by Yamada-Ika** [comment]
@kota-shiokara Thanks! Assigned!
