### ISSUE TITLE
On the event map screen, the background color of the top app bar differs from the Figma design when scrolling

### ISSUE THREAD

**Issue by Yamada-Ika** [DroidKaigi/conference-app-2024#595]
|  actual  |  expect  |
| ---- | ---- |
| <img width="300" alt="スクリーンショット 2024-08-18 10 47 45" src="https://github.com/user-attachments/assets/00753edb-ff04-4851-83d4-18bca4eb149c"> | <img width="300" alt="スクリーンショット 2024-08-18 10 48 02" src="https://github.com/user-attachments/assets/a40f0852-7f7a-4cf1-ace0-dc6ab3a87c33"> |

**Comment by nanaten** [comment]
🙋‍♀

**Comment by Yamada-Ika** [comment]
@nanaten Thanks! Assigned!

**Comment by nanaten** [comment]
@Yamada-Ika 
I couldn't confirm this issue. It might have been resolved by another fix. 
I'm attaching the current screenshot, so please check it.

<img src="https://github.com/user-attachments/assets/41a77e7f-d3be-40a9-9000-4cef7c084d0a" width=300/>

**Comment by Yamada-Ika** [comment]
@nanaten Thank you for checking. It seems like this issue has already been resolved. I am very sorry, especially after you took the time. I will close this issue now. 🙇

**Comment by Yamada-Ika** [comment]
@nanaten Alternatively, if you don't mind, how about this issue? 
https://github.com/DroidKaigi/conference-app-2024/issues/578

**Comment by Yamada-Ika** [comment]
Upon checking earlier, it seems that #578 has not yet been resolved.

**Comment by Yamada-Ika** [comment]
I will make sure that someone else works on https://github.com/DroidKaigi/conference-app-2024/issues/578.
