### ISSUE TITLE
On the favorite screen, the background color of the top app bar differs from the Figma design when scrolling

### ISSUE THREAD

**Issue by Yamada-Ika** [DroidKaigi/conference-app-2024#596]
|  actual  |  expect  |
| ---- | ---- |
| <img width="300" alt="スクリーンショット 2024-08-18 10 49 47" src="https://github.com/user-attachments/assets/f9f24b78-f43c-436b-9e3a-66b60eb96fcb"> | <img width="300" alt="スクリーンショット 2024-08-18 10 50 12" src="https://github.com/user-attachments/assets/7cb871ed-1438-4453-bf86-ace8f0e749e0"> |

**Comment by nishimy432** [comment]
🙋

**Comment by Yamada-Ika** [comment]
@nishimy432 Thanks! Assgined!
