### ISSUE TITLE
On the about screen, the background color of the top app bar differs from the Figma design when scrolling

### ISSUE THREAD

**Issue by Yamada-Ika** [DroidKaigi/conference-app-2024#597]
|  actual  |  expect  |
| ---- | ---- |
| <img width="300" alt="スクリーンショット 2024-08-18 10 50 58" src="https://github.com/user-attachments/assets/f0fcd2cf-a75c-4e22-959b-02aac4c4e054"> | <img width="300" alt="スクリーンショット 2024-08-18 10 51 36" src="https://github.com/user-attachments/assets/11e406e0-0053-423e-b246-caf584f63ca4"> |

**Comment by chickenjr** [comment]
:raising_hand:

**Comment by Yamada-Ika** [comment]
@chickenjr Thanks! Assigned!
