### ISSUE TITLE
Padding of element per Time in TimetableList is different from Figma

### ISSUE THREAD

**Issue by kosenda** [DroidKaigi/conference-app-2024#599]
## Overview
As the title says, the Padding per time appears to be half of Figma
The same is true for FavoriteScreen and SearchScreen as well as TimetableScreen.

|Figma|Actual|
|---|---|
|<img src="https://github.com/user-attachments/assets/d5175088-992a-4b86-9091-1c0a3eecc8de" width="300">|<img src="https://github.com/user-attachments/assets/0b00525a-c9b1-4306-a1de-a19666594657" width="300">|

## Figma
https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI?node-id=54876-39860&t=HSvuYQHvkIqBfsAc-4

**Comment by matsuurayuki1219** [comment]
i would like to try it !!

**Comment by takahirom** [comment]
Thanks! Assigned 👍
