### ISSUE TITLE
Use real API for EventMap screen

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2024#602]
Now the development environment API is ready!
The end point is
 > events/droidkaigi2024/projects

We need to change here.

https://github.com/DroidKaigi/conference-app-2024/blob/main/core/data/src/commonMain/kotlin/io/github/droidkaigi/confsched/data/eventmap/EventMapApiClient.kt#L15

**Comment by geckour** [comment]
I want to try it! 🙋‍♂️

**Comment by takahirom** [comment]
@geckour Thanks! Because this is a very high priority issue, if you could do this quickly, that would be great. 👍

**Comment by geckour** [comment]
@takahirom 
I have a question 🙏 
This issue's scope is just to replace the endpoint to mentioned one by you?
We don't need to switch current endpoint (`/events/droidkaigi2024/eventmap`) and mentioned one according to the build environments?
