### ISSUE TITLE
TimetableItemTag may partially disappear when the font size is large

### ISSUE THREAD

**Issue by kosenda** [DroidKaigi/conference-app-2024#608]
## Overview
As the title says, the tags disappear when the font size is large. Maybe using FlowRow is the way to go.

|No problem|Problem|
|---|---|
|<img src="https://github.com/user-attachments/assets/9b912701-7e84-485a-b8ff-588c7426a28e" width="300">|<img src="https://github.com/user-attachments/assets/62405bfc-a72b-4227-abd9-b86e2a5dd421" width="300">|

**Comment by hicka04** [comment]
🙋
