### ISSUE TITLE
Micro-interaction of favorite does not work when navigationBar is Rail instead of Bottom

### ISSUE THREAD

**Issue by kosenda** [DroidKaigi/conference-app-2024#611]
## Overview
Please close if this is what you intended 🙇
I think it would be better to have animation even for Rail's NavigationBar.

|Bottom|Rail|
|---|---|
|<video src="https://github.com/user-attachments/assets/e0f4260d-cb26-4fa2-b05e-a580a4aac9da">|<video src="https://github.com/user-attachments/assets/0472379d-1a1c-47de-9a6f-0677fea1ff04">|

**Comment by ked4ma** [comment]
I'll try it :raised_back_of_hand:

**Comment by takahirom** [comment]
Thanks! Assigned 👍
