### ISSUE TITLE
In AboutScreen, description is closer to left edge of screen when device is long horizontally.

### ISSUE THREAD

**Issue by kosenda** [DroidKaigi/conference-app-2024#612]
## Overview
As the title says, the description should be in the middle, not to the left.

|Figma|Actual|
|---|---|
|<img src="https://github.com/user-attachments/assets/1fa7c46c-534c-4b38-9a3c-3e5b695edabb" width=350>|<img src="https://github.com/user-attachments/assets/69de88bc-9108-4540-810d-deebbbf68b99" width=350>|

**Comment by Pon57** [comment]
🙋‍♂️

**Comment by takahirom** [comment]
Thanks! Assgined👍
