### ISSUE TITLE
No padding at the end of SponsorsScreen

### ISSUE THREAD

**Issue by kosenda** [DroidKaigi/conference-app-2024#614]
## Overview
Unlike Figma, Actual seems to have less trailing padding. It looks like at least 40.dp is needed.

|Figma|Actual|
|---|---|
|<img src="https://github.com/user-attachments/assets/a17df8a6-a302-4412-9bb8-f05f132125d0" width="300">|<img src="https://github.com/user-attachments/assets/0bdd649f-5334-4c97-a17b-b7cbda9ad097" width="300">|

## Figma
https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI?node-id=55054-77637&t=DdQsFjracJhlzCMF-4

**Comment by yuheikawakami** [comment]
🙋

**Comment by takahirom** [comment]
Thanks! Assigned 👍
