### ISSUE TITLE
Timetable Feature: Fix an action of tapped favorite button

### ISSUE THREAD

**Issue by MrSmart00** [DroidKaigi/conference-app-2024#617]
## Overview

Currently, timetable cell's favorite button tapped action isn't correct.

## Goal

- change action when tapped favorite button action to switching heart icon.

## Movie

<video src="https://github.com/user-attachments/assets/35f3bdb6-0c7b-42c9-909b-be1a3fb9d392" />

**Comment by charles-b-stb** [comment]
これは自分のブランチでなみたことがないです。もしかしたらマージで何かうまくいかなかったでしょうかな？

見てみます。

**Comment by charles-b-stb** [comment]
@MrSmart00 @takahirom @shin-usu 
Checking back on figma, there does not seem to be an account of the bookmark toast on this particular page (only on other pages). Maybe we don't need the bookmark toast on Timetable list view?
