### ISSUE TITLE
Timetable Feature: Add margin around Timetable Grid display

### ISSUE THREAD

**Issue by MrSmart00** [DroidKaigi/conference-app-2024#618]
## Overview

Need margin for Timetable Grid display because its no margin currently.

<img src='https://github.com/user-attachments/assets/cbcb900f-096b-4cbd-ad73-67ff88c56594' width=400 />

## Goal

Trailing margin 16px
Bottom margin also below custom tabbar on 16px

**Comment by shunsugawara** [comment]
🙋‍♂️
