### ISSUE TITLE
ProfileCard: OGP image to share

### ISSUE THREAD

**Issue by mikanIchinose** [DroidKaigi/conference-app-2024#647]
## Spec
Generate a image bellow when you share

<img height=700 src="https://github.com/user-attachments/assets/b726f32c-a685-48d7-8d14-2aecf1e267c3">

https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI?node-id=58136-36586&t=T9cdyGXsD7ZwFCN8-4

## Blocking Issue
- #422

**Comment by gargVader** [comment]
Can you explain more on what is required to be done?
