### ISSUE TITLE
In TimetableItemDetailScreen, the translation state disappears when the favorite button is pressed to return to the FavoriteScreen

### ISSUE THREAD

**Issue by kosenda** [DroidKaigi/conference-app-2024#655]
## Overview
- Similar to #510, I think it would not be good if the translated state is not translated when the user transitions to the favorites screen with the translated state and returns to the favorites screen.

https://github.com/user-attachments/assets/8c2f4846-2015-4b41-97a0-860d3a6b2cc7

I think we can use rememberRetained here.
https://github.com/DroidKaigi/conference-app-2024/blob/819be2868e992aafe5b3629b09d113c09d36a9e5/feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/TimetableItemDetailPresenter.kt#L51

**Comment by hiesiea** [comment]
I'd like to try this issue 🙋

**Comment by takahirom** [comment]
Thanks! Assigned 👍
