### ISSUE TITLE
Snack Bar and BottomBarTabs Overlap on the Event Map

### ISSUE THREAD

**Issue by JoesPredator** [DroidKaigi/conference-app-2024#659]
### Overview
As the title suggests snackbar and BottomBarTabs  overlap

### To Reproduce
offline and opening the event map.

https://github.com/user-attachments/assets/ba936846-629a-4c70-bfd2-32c547e6c565

### Proposed 
If **contentWindowInsets** is set for EventMapScreen like it is for other Screen classes, it might fix the issue.

https://github.com/DroidKaigi/conference-app-2024/blob/9f3e72052486fbc3de0a421c9b8eb8e4180a8da4/feature/eventmap/src/commonMain/kotlin/io/github/droidkaigi/confsched/eventmap/EventMapScreen.kt#L100-L118

**Comment by obaya884** [comment]
I fixed this issue in the PR #675 !
Please check it. 🙏
