### ISSUE TITLE
Pressing the back key during transition animation causes the originating screen to terminate

### ISSUE THREAD

**Issue by JoesPredator** [DroidKaigi/conference-app-2024#661]
### Overview
When clicking on an item in the timetable to transition to the detail screen, an animation occurs.

However, if the back key is pressed during the animation, it seems that the originating screen is terminated.

### To Reproduce

https://github.com/user-attachments/assets/d147061e-3690-49b8-9ea8-1c24ea233bfd

**Comment by takahirom** [comment]
I think this is an edge case, but it will result in a very strange status when we press the back key. If we could fix this, that would be great.

**Comment by Pon57** [comment]
🙋‍♂️

**Comment by mikanIchinose** [comment]
Assigned!
