### ISSUE TITLE
TopAppBar color may not switch properly in ProfileCardScreen

### ISSUE THREAD

**Issue by kosenda** [DroidKaigi/conference-app-2024#690]
## Overview
This phenomenon is caused by the following operations
- Registering a profile
- After registering, go to the edit screen and then update
- After registering, use NavigationBar to move to the edit screen, then use NavigationBar to move to another screen, then use NavigationBar to move to the profile card.

https://github.com/user-attachments/assets/49b4b315-2011-44ef-a7b0-0b453fa517a8

**Comment by yuchan2215** [comment]
#707 This Pull Request might resolve the issue.

**Comment by takahirom** [comment]
I think it is solved now. Thanks @yuchan2215 !
