### ISSUE TITLE
Make the timetable times sticky

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2024#699]
Make them stick to the top, and when the next time comes, the previous time should disappear.
<img width="166" alt="image" src="https://github.com/user-attachments/assets/24d67824-6fb6-4ca0-bd90-ca7d040d0bb6">

**Comment by ked4ma** [comment]
:raised_hand_with_fingers_splayed:

**Comment by takahirom** [comment]
Thanks! Assigned 👍
