### ISSUE TITLE
Adjust the spacing between the up button and title to match the Figma design.

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2024#702]
<img width="277" alt="image" src="https://github.com/user-attachments/assets/68b6f18b-edbb-4e36-906d-bf3fc2bc13fd">
<img width="188" alt="image" src="https://github.com/user-attachments/assets/022ace28-07b1-46c4-ba64-fe69230b4e5c">
https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI?node-id=54795-26746

**Comment by choi-woo-sung** [comment]
🙋

**Comment by takahirom** [comment]
Thanks! Assigned 👍

**Comment by takahirom** [comment]
I'm not sure, but can we use medium?
https://developer.android.com/develop/ui/compose/components/app-bars#medium

**Comment by choi-woo-sung** [comment]
@takahirom 
thank you 

<img width="294" alt="image" src="https://github.com/user-attachments/assets/c788a4d2-86b3-4c16-af10-cebd045d6583">

**Comment by choi-woo-sung** [comment]
@takahirom 
I dont 'know why test fail....

**Comment by takahirom** [comment]
Thank you for letting me know! Don't worry.
First, I think you can remove the unused import.

https://github.com/DroidKaigi/conference-app-2024/actions/runs/10633335229/job/29479517095?pr=753

> e: file:///home/runner/work/conference-app-2024/conference-app-2024/feature/contributors/src/commonMain/kotlin/io/github/droidkaigi/confsched/contributors/ContributorsScreen.kt:29:52 Unresolved reference 'handleOnClickIfNotNavigating'.

---

Second, you can open SponsorsScreenTest and click Run the test!
<img width="546" alt="image" src="https://github.com/user-attachments/assets/14d96e8e-2c8b-4663-b96c-6fd13f603a99">

And then the supporters are not displayed.

<img width="586" alt="image" src="https://github.com/user-attachments/assets/bf57c3d6-db8b-4b9e-82be-bdbdf1e0c0ef">


```
SponsorsScreenTest > runTest[SponsorsScreen - when server is operational - when launch - when scroll to supporters header - it should display supporters sponsors] STARTED

SponsorsScreenTest > runTest[SponsorsScreen - when server is operational - when launch - when scroll to supporters header - it should display supporters sponsors] FAILED
    java.lang.AssertionError: Assert failed: The component is not displayed!
        at androidx.compose.ui.test.AssertionsKt.assertIsDisplayed(Assertions.kt:34)
        at io.github.droidkaigi.confsched.testing.robot.SponsorsScreenRobot.checkSponsorItemsDisplayedByRangeAndSponsorType(SponsorsScreenRobot.kt:100)
        at io.github.droidkaigi.confsched.testing.robot.SponsorsScreenRobot.checkDisplaySupportersSponsors(SponsorsScreenRobot.kt:85)
        at io.github.droidkaigi.confsched.sponsors.SponsorsScreenTest$Companion$behaviors$1$1$2$4$2.invokeSuspend$lambda$0(SponsorsScreenTest.kt:75)
        at io.github.droidkaigi.confsched.testing.robot.DefaultCaptureScreenRobot.captureScreenWithChecks(MiniRobots.kt:106)
        at io.github.droidkaigi.confsched.testing.robot.DefaultScreenRobot.captureScreenWithChecks(MiniRobots.kt)
```

How about adding this to SponsorsScreenRobot?

```kotlin
fun scrollToBottom() {
        composeTestRule
            .onNode(hasTestTag(SponsorsListLazyVerticalGridTestTag))
            .performScrollToNode(
                hasTestTag(SponsorsListSponsorItemTestTagPrefix.plus(Sponsor.fakes().last().name)),
            )
    }
```

**Comment by choi-woo-sung** [comment]
@takahirom 
Thank you for your help. i fix it.
