### ISSUE TITLE
Adjust the timetable day tab design to match the Figma design

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2024#704]
Device
<img width="401" alt="image" src="https://github.com/user-attachments/assets/dec9541a-fe4f-400e-954b-219251469ef7">
Figma
<img width="698" alt="image" src="https://github.com/user-attachments/assets/0929a99f-c26c-42ff-9ebc-05e68f5955fd">
https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI?node-id=54795-26746&t=BC9LMKHWIaOtLDcJ-0

**Comment by r4wxii** [comment]
🙋

**Comment by takahirom** [comment]
Thanks! Assigned 👍

**Comment by takahirom** [comment]
Sorry. I estimated incorrectly. I think this is a higher priority issue because it is shown to all users. So if you have any problems, please let me know. 🙏
