### ISSUE TITLE
In FavoriteScreen on a small device, it would be better to make EmptyView scrollable.

### ISSUE THREAD

**Issue by kosenda** [DroidKaigi/conference-app-2024#716]
## Overview
The following is the case of SplitScreen, but it would be better to be able to scroll the screen because text and other items are hidden.

https://github.com/user-attachments/assets/0a9ead20-1b78-4696-b09d-4a5d46da0746

**Comment by Yamada-Ika** [comment]
@kosenda Thank you for creating the issue!
 It seems like this issue is duplicated. https://github.com/DroidKaigi/conference-app-2024/issues/517
Are these issues the same?

**Comment by kosenda** [comment]
@Yamada-Ika 
I am very sorry 🙇
Thank you for letting me know!
We will close this one!
