### ISSUE TITLE
Fix iOS Compose Bottom Navigation selected position

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2024#726]
![image](https://github.com/user-attachments/assets/247e6613-e773-471e-84b3-11c6d5d92358)

I think we need to copy the implementation from KaigiApp. It should be a relatively straightforward task, but you'll need to build the iOS app and verify that it works correctly.
https://github.com/DroidKaigi/conference-app-2024/blob/main/app-android/src/main/java/io/github/droidkaigi/confsched/KaigiApp.kt#L271-L276
https://github.com/DroidKaigi/conference-app-2024/blob/main/app-ios-shared/src/commonMain/kotlin/io/github/droidkaigi/confsched/shared/IosComposeKaigiApp.kt#L236-L238
iOS Build
https://github.com/DroidKaigi/conference-app-2024/tree/main/app-ios

**Comment by Corvus400** [comment]
I would like to address this issue. 🙋‍♂️
