### ISSUE TITLE
Fix External Links in iOS Compose Multiplatform

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2024#727]
We are currently commenting out `externalNavController::navigate`. I believe we can pass a lambda from iOS and use it for external link navigation. I would like to open Safari for these links.
https://github.com/DroidKaigi/conference-app-2024/blob/main/app-ios-shared/src/commonMain/kotlin/io/github/droidkaigi/confsched/shared/IosComposeKaigiApp.kt

**Comment by Corvus400** [comment]
I would like to address this issue. 🙋‍♂️

**Comment by takahirom** [comment]
Thanks! Assigned 👍
