### ISSUE TITLE
The tint color of the icons used on the 'about' screen differs from what is shown in Figma

### ISSUE THREAD

**Issue by Yamada-Ika** [DroidKaigi/conference-app-2024#728]
|  actual  |  expected  |
| ---- | ---- |
| <img width="300" alt="スクリーンショット 2024-08-22 23 04 59" src="https://github.com/user-attachments/assets/4f8932ac-bd50-4ed5-9ba8-8a6811a556fe"> | <img width="300" alt="スクリーンショット 2024-08-22 23 05 09" src="https://github.com/user-attachments/assets/ee48dd12-cfd2-4b7c-b37c-34b36988284a"> | 

Figma
- https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI?node-id=54985-75945&t=Sl8amZjkKhoYkzn5-4

**Comment by ked4ma** [comment]
:raised_hand_with_fingers_splayed:

**Comment by Yamada-Ika** [comment]
@ked4ma Thanks! Assigned!
