### ISSUE TITLE
Add translations for profile card screen

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2024#729]
We have "Share" and "Edit" buttons, but we don't have translations for Japanese.
Please use Compose Resources to display the translation
https://github.com/DroidKaigi/conference-app-2024/blob/b69506419c6c5555aae87d9e6f485ecbec15d7f9/feature/profilecard/src/commonMain/composeResources/values/strings.xml

https://github.com/DroidKaigi/conference-app-2024/blob/b69506419c6c5555aae87d9e6f485ecbec15d7f9/feature/profilecard/src/commonMain/kotlin/io/github/droidkaigi/confsched/profilecard/ProfileCardScreen.kt#L750

**Comment by mannodermaus** [comment]
✋
