### ISSUE TITLE
The QR code generated from the ProfileCard is difficult to scan with a QR code reader.

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2024#730]
It's supposed to link to https://google.com/, but I can't scan it successfully.
<img width="234" alt="image" src="https://github.com/user-attachments/assets/3439a665-dee7-444c-bb1e-c4492196e3f9">

**Comment by takahirom** [comment]
Well, when I use Google Lens it's difficult, but if I use a third-party scanner I'm able to scan it. Let's lower the priority.

**Comment by yoshida0261** [comment]
🙋
