### ISSUE TITLE
Share ProfileCard from an iOS Compose Multiplatform app

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2024#731]
I think we can pass a lambda function from the iOS app so we can pass the image.
https://github.com/DroidKaigi/conference-app-2024/blob/50760b0f0ddbc9afb6958cbea5c127ca37dbb5df/app-ios-shared/src/commonMain/kotlin/io/github/droidkaigi/confsched/shared/IosComposeKaigiApp.kt#L104

**Comment by Corvus400** [comment]
I would like to address this issue. 🙋‍♂️

**Comment by takahirom** [comment]
Thanks as always!
