### ISSUE TITLE
In ProfileCardScreen, edited content disappears when screen size is changed while editing a Profile

### ISSUE THREAD

**Issue by kosenda** [DroidKaigi/conference-app-2024#737]
## Overview
If the screen size is changed while editing a profile, the activity will be regenerated and the edited content will be lost and displayed as a card.

https://github.com/user-attachments/assets/6e165aba-2e10-452f-b1b9-22b128e31da7

## Solution I came up with
We can suppress Activity regenerations by adding a setting to `AndroidManifest.xml`, as shown below.

[Android developers - Restrict activity recreation](https://developer.android.com/guide/topics/resources/runtime-changes#restrict-activity)

**Comment by kosenda** [comment]
@takahirom 
Sorry to bother you!
Would the above solution not be good...?

**Comment by takahirom** [comment]
I think we can just use rememberRetained here. 👀 
https://github.com/DroidKaigi/conference-app-2024/blob/04df9da6f5f81803ca45acdecaacd3a434ead81e/feature/profilecard/src/commonMain/kotlin/io/github/droidkaigi/confsched/profilecard/ProfileCardScreenPresenter.kt#L108

**Comment by takahirom** [comment]
And for nickname we can use rememberSavable as we do in AndroidView
https://github.com/DroidKaigi/conference-app-2024/blob/ea797f039bbbd362a23dff542a835ede3826c8d1/feature/profilecard/src/commonMain/kotlin/io/github/droidkaigi/confsched/profilecard/ProfileCardScreen.kt#L352

**Comment by kosenda** [comment]
It's certainly better that way...!

**Comment by takahirom** [comment]
However, for imageByteArray, I think it's better to keep it as remember to avoid issues with large SavedInstanceState

**Comment by Songgyubin** [comment]
🙋 I want to try it!

**Comment by takahirom** [comment]
Thanks! Assigned 👍
