### ISSUE TITLE
Add scrolled screen test for FavoritesScreenTest

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2024#746]
For your reference
TimetableScreenTest 
https://github.com/DroidKaigi/conference-app-2024/blob/main/feature/sessions/src/androidUnitTest/kotlin/io/github/droidkaigi/confsched/sessions/TimetableScreenTest.kt#L79
FavoritesScreenTest
https://github.com/DroidKaigi/conference-app-2024/blob/main/feature/favorites/src/androidUnitTest/kotlin/io/github/droidkaigi/confsched/favorites/FavoritesScreenTest.kt

**Comment by ParkJong-Hun** [comment]
Would I do it?

**Comment by takahirom** [comment]
Thanks! Assigned 👍
