### ISSUE TITLE
Fix profile card share text

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2024#747]
English:  `Check out my DroidKaigi Profile Card! Let's connect at the event. #DroidKaigi`
Japanese: `DroidKaigiのプロフィールカードを作成しました！イベントでつながりましょう。#DroidKaigi`

https://github.com/DroidKaigi/conference-app-2024/blob/730d283b94c2f2b356dd5c0d1edc335b0dbf8a23/feature/profilecard/src/commonMain/kotlin/io/github/droidkaigi/confsched/profilecard/ProfileCardScreen.kt#L303

https://github.com/DroidKaigi/conference-app-2024/blob/8d81f2667d804096cc22f35b501a8d79ac2e9e4a/feature/profilecard/src/commonMain/composeResources/values/strings.xml#L1

**Comment by mannodermaus** [comment]
✋

**Comment by takahirom** [comment]
Thanks!
