### ISSUE TITLE
Make the translation button more visible

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2024#748]
We have a translation button in the right top menu, but we are currently showing the session's default language. We would like to make it more visible.
The designer said you can start working now using the design in Figma.
![image](https://github.com/user-attachments/assets/a5bc31ed-d025-4ad2-9133-1cccc914ba19)
https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI?node-id=54795-26746

**Comment by takahirom** [comment]
This issue is assigned to @mangano-ito. 
@mangano-ito
I need a comment from you to put the assignment (GitHub specification) . Could you please leave a comment on this issue?

(Please check the context for more details.
https://github.com/DroidKaigi/conference-app-2024/pull/679 )

**Comment by mangano-ito** [comment]
I'll do it! 🙋

**Comment by takahirom** [comment]
Thanks!
