### ISSUE TITLE
The system bar appearance is incorrect on the ProfileCardScreen

### ISSUE THREAD

**Issue by mannodermaus** [DroidKaigi/conference-app-2024#762]
As per Figma, the tint/text color of the system bar should be dark to contrast more nicely against the light backgrounds of the `ProfileCardScreen`:

<img width="1348" alt="Screenshot 2024-08-24 at 9 37 12" src="https://github.com/user-attachments/assets/f047ec28-baeb-42c0-ba61-43c2582b0b77">

Currently, this color stays light (because it looks good for all other screens of the app). We will need to add a way to control the system bar appearance on a per-screen basis, changing the color as needed depending on the underlying background.

![wrong](https://github.com/user-attachments/assets/66702d26-5671-4976-830f-d3a0d431f0e2)

**Comment by mannodermaus** [comment]
✋

**Comment by takahirom** [comment]
Thanks! Assigned 👍
