### ISSUE TITLE
ProfileCardScreen does not require Snackbar

### ISSUE THREAD

**Issue by kosenda** [DroidKaigi/conference-app-2024#766]
## Overview
ProfileCardScreen displays a Snackbar when editing or creating a profile, but the Snackbar is covered by input fields and buttons, inhibiting input. Therefore, it would be better if the Snackbar could be turned off with a tap or swipe.

https://github.com/user-attachments/assets/dc2d0653-0235-4d5a-b926-375bfdae69e0

**Comment by kosenda** [comment]
I would like to try this issue if I should be 🖐️

**Comment by Corvus400** [comment]
In the first place, this snack bar is getting in the way of the operation, and I would like it not to be displayed if possible. 
(This snack bar was quite an obstacle when implementing profile screens, etc. and fixing bugs.🥺)

@takahirom 
Is it necessary to display the snack bar?

**Comment by takahirom** [comment]
I don't think we need the snackbar. 👍

**Comment by kosenda** [comment]
I thought it would be a good idea to change the name of the issue, so I did.

**Comment by Corvus400** [comment]
I would like to work on this task.🙋‍♂️

**Comment by takahirom** [comment]
Thanks as always!
