### ISSUE TITLE
Move notCompatibleWithConfigurationCache config to KmpPlugin from KmpKtorfitPlugin

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2024#772]
I think we can use [`withPlugin`](https://docs.gradle.org/current/kotlin-dsl/gradle/org.gradle.api.plugins/-plugin-manager/with-plugin.html) or something to do it.
https://github.com/DroidKaigi/conference-app-2024/pull/744/files

**Comment by Aniokrait** [comment]
🙋‍♂️

**Comment by takahirom** [comment]
Thanks! Assigned 👍
