### ISSUE TITLE
In TimetableList, Behavior when scrolling the date switching tab is not implemented.

### ISSUE THREAD

**Issue by kosenda** [DroidKaigi/conference-app-2024#782]
## Overview
As per the specifications in Figma below, the date switching tab must be shown or hidden by scrolling.

<img width="539" alt="image" src="https://github.com/user-attachments/assets/50b4def6-cfd3-488c-9b0f-8760586b727e">

## Figma
https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI?node-id=54888-45706&t=94gBozQ71SBBtf4Y-4

## Actual

https://github.com/user-attachments/assets/87423fbe-3685-4a4c-934b-b1acfabc6932

**Comment by shunm-999** [comment]
🙋
