### ISSUE TITLE
Maybe we should share the date with the session sharing

### ISSUE THREAD

**Issue by kosenda** [DroidKaigi/conference-app-2024#783]
## Oveview
Sorry if this is unnecessary 🙇
Currently, the following is shared when you share, but I thought it might be better to have a date.

```
[Jellyfish] 10:00 - 10:15
Welcome Talk
https://2024.droidkaigi.jp/timetable/85841558-4423-4ce9-859a-83a2a11235c6
```

https://github.com/DroidKaigi/conference-app-2024/blob/390a9956c22c6fd04366457a49f062ae45a226c0/app-android/src/main/java/io/github/droidkaigi/confsched/KaigiApp.kt#L356-L362

**Comment by Corvus400** [comment]
I don't remember exactly, but this may be the reason why I did not add the date. :thinking: 
https://github.com/DroidKaigi/conference-app-2023/pull/1029#discussion_r1310517689

**Comment by takahirom** [comment]
Thanks. I don't think it's a bad idea to have a method just for sharing.

**Comment by sadashi-ota** [comment]
If it's okay to add this feature, I'd like to do it. 🙋

**Comment by takahirom** [comment]
Thanks!
