### ISSUE TITLE
EventMapItem text color is different from Figma

### ISSUE THREAD

**Issue by kosenda** [DroidKaigi/conference-app-2024#784]
## Overview
As the title says, when I look at Figma, there are some places where the color that should be the common color is the room color (primary color).

|Figma|Actual|
|---|---|
|<img src="https://github.com/user-attachments/assets/4ea8fd93-90a6-44d0-af6b-edccb2458a5c" width="300">|<img src="https://github.com/user-attachments/assets/4de1cba9-bfb7-4978-8526-b82e9ae3cf6b" width="300">|

**Comment by shxun6934** [comment]
I try this Issue! 🙋‍♂️

**Comment by takahirom** [comment]
Thanks! Assigned 👍
