### ISSUE TITLE
In SearchScreen, design is added for there were no search results using filters with no input values

### ISSUE THREAD

**Issue by kosenda** [DroidKaigi/conference-app-2024#798]
## Overview
A design has been added for when there is no text input, only filtering and no results.

<img width="250" alt="image" src="https://github.com/user-attachments/assets/525b11c6-65d2-4d75-a0e0-469c27f08aad">

## Figma
https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI?node-id=58871-8744&t=WGCdhOBgDfcbOcP9-4

## Course of events 
Conversations in Figma below

https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC?node-id=54965-73644#923462203

**Comment by nishimy432** [comment]
:raising_hand:
