### ISSUE TITLE
Search Feature

### ISSUE THREAD

**Issue by charles-b-stb** [DroidKaigi/conference-app-2024#80]
Search feature for the app. If we have time
<img width="699" alt="スクリーンショット 2024-06-26 20 55 58" src="https://github.com/DroidKaigi/conference-app-2024/assets/17753214/caf1907d-49ce-4f16-bf1a-1bfe10f7adfc">

**Comment by kitakkun** [comment]
Can I work on this issue?

**Comment by NUmeroAndDev** [comment]
Thanks! Assigned 👍
