### ISSUE TITLE
Validate that the URL in the ProfileCard is correct

### ISSUE THREAD

**Issue by kosenda** [DroidKaigi/conference-app-2024#800]
## Overview
In the following input fields, in addition to checking for empty characters, it is necessary to check for a valid URL.

<img width="439" alt="image" src="https://github.com/user-attachments/assets/2cd3cd63-877f-4f07-be60-8028ef5537db">

## Course of events
Conversations in Figma below

> デザインを見直しました。ユーザーがSNSリンクを入力するとき、コピー＆ペーストが多いと思うので、デフォルトで『http://』を表示しないようにUIを変えてみました！
> 
> URLが正しくない場合にはエラーが出るようにしたいので、正規表現等を用いてチェックしていただく認識であっております。
> 
> URLが正常かどうかの判定方法はおまかせいたします🙇‍♀️ 

(Google Translator  JP -> EN)
> We've revised the design. We think that users often copy and paste when entering SNS links, so we changed the UI so that it doesn't display "http://" by default!
> 
> We want to display an error if the URL is incorrect, so we understand that you will need to check it using regular expressions, etc.
> 
> We'll leave it up to you to decide whether the URL is valid or not🙇‍♀️

https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC?node-id=56929-31978#923773941

**Comment by Aniokrait** [comment]
✋

**Comment by Aniokrait** [comment]
@nobonobopurin
I'm thinking of changing the message for invalid url from "リンクを入力してください" to "URLの形式が正しくありません" 
so that the message becomes more natural.
What do you think?

**Comment by nobonobopurin** [comment]
@Aniokrait Thank you for the suggestion! 「URLの形式が正しくありません」 seems clearer and better.

**Comment by Aniokrait** [comment]
I will add English message too.
new message: "The URL format is incorrect."
