### ISSUE TITLE
In ProfileCardScreen, expand the tap area of the button to be edited

### ISSUE THREAD

**Issue by kosenda** [DroidKaigi/conference-app-2024#801]
## Overview
As the title says, the button to edit should be in the same tap area as the button for sharing one above.

<img width="459" alt="image" src="https://github.com/user-attachments/assets/ad9ee540-e2e6-423b-9d7a-4aedb9da9a26">

## Figma
https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI?node-id=55644-39120&t=mTxTzXFOMIuOie4o-4

## Course of events
Conversations in Figma below
https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC?node-id=55644-39120#923780086

**Comment by fukuroow** [comment]
🙋
