### ISSUE TITLE
In ContirbutorsScreen and StaffScreen, add padding to the end of the List

### ISSUE THREAD

**Issue by kosenda** [DroidKaigi/conference-app-2024#802]
## Overview
As the title says, you need to put padding at the end of the list.
There is no padding in the application at this time.

<img width="300" alt="image" src="https://github.com/user-attachments/assets/0e3b39b4-6b0d-4a5f-b7ad-889fe2d03821">

## Figma
https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI?node-id=55054-77174&t=mTxTzXFOMIuOie4o-4

## Course of events

> 下40px空けていただきたいです！UI更新いたしました 🙏

(Google translator JP -> EN)
> I would like to have 40px space at the bottom!

https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC?node-id=54953-64722#923844162

**Comment by takarabe-hamuyatti** [comment]
🙌

**Comment by takahirom** [comment]
@takarabe-hamuyatti Thanks!
