### ISSUE TITLE
SettingsScreen design added to Figma.

### ISSUE THREAD

**Issue by kosenda** [DroidKaigi/conference-app-2024#803]
## Overview
It looks like it needs to be implemented in accordance with Figma.

|Actual|Figma|
|---|---|
|<img src="https://github.com/user-attachments/assets/e222b497-831c-44f9-89b8-55242239a7ff" width="300">|<img src="https://github.com/user-attachments/assets/da4a91d9-f362-40e5-b887-c1fd749b368f" width="300">|

## Figma
https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI?node-id=58871-8452&t=mTxTzXFOMIuOie4o-4

## Course of events
Conversations in Figma below
https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC?node-id=54982-75342#923772969

**Comment by ked4ma** [comment]
:raised_hand_with_fingers_splayed:

**Comment by ked4ma** [comment]
this is assigned to kosenda-san 👀 
should i close the pr?
if so, please notice me 🙏

**Comment by takahirom** [comment]
@ked4ma 
Sorry. I made a mistake. I've changed the assigned person. 🙇

**Comment by ked4ma** [comment]
Thank you!!! 🙏🙏🙏
