### ISSUE TITLE
In TimetableScreen, buttons placement is different from Figma and tap area is narrower

### ISSUE THREAD

**Issue by kosenda** [DroidKaigi/conference-app-2024#804]
## Overview
It is hard to tell, but the tap area is the same size as the icon, which is different from Figma. Also, I think RIPPLE should be a circle to match the others.

https://github.com/user-attachments/assets/c5269137-daa5-493d-9e88-bc40d4d5ef10

## Figma
https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI?node-id=54849-12900&t=Zb89cz5zYV8m65VP-4

<img width="552" alt="image" src="https://github.com/user-attachments/assets/112d143c-493e-416c-9e3c-0405ee89392e">

**Comment by ritsukiotsuka** [comment]
I'd like to work on this🙋‍♂️

**Comment by mikanIchinose** [comment]
Thanks. Assigned!
