### ISSUE TITLE
[Suggestion] Display the QrCode of Profile Card in the wear application.

### ISSUE THREAD

**Issue by hiroaki404** [DroidKaigi/conference-app-2024#808]
Display QrCode on wear device to encourage communication during the event.
It will be possible to display the QrCode without opening the mobile app.
And it can increase interest in wear app development.

Concerns.
- The opportunity to use the rich and excellent profile card in the mobile app may be reduced just a little.
- Implementation of apple watch. Not sure if anyone is familiar with this.
- Project will be somewhat complicated.
- How to deploy the wear app.

If you agree, we will consider how to implement the rough specification.
Please feel free to reject it if you don't like it, as it may have an impact.

**Comment by takahirom** [comment]
I think it is good. However, I'm not sure if we can release it on Google Play.
But I think we can work on this!

**Comment by hiroaki404** [comment]
Thank you. I try to think.

**Comment by hiroaki404** [comment]
### Specifications
When the profile screen is opened in mobile, if the profile has already been set, send it to the wear app.
I think the UI is unnecessary because most users do not need to be aware of the wear app.


### Deployment
I think the only way to make it easy for developers to download is to release it on Google Play. It is hard for me to think of a way to support it.

I think the limitation is that they have to be built from Android Studio. I think it would be better to describe how to build. I describe it to `README.MD` of the module.

### Apple Watch
I don't have enough knowledge about Apple Watch support, but I will implement it with KMP as much as possible.

### Module Configuration
We will use [DataClient](https://developer.android.com/training/wearables/data/data-items?hl=ja) to send profile links from mobile to watch.
The module configuration is follows.

- app-android
- app-ios
- app-ios-shared
- app-wear(add)
- core
- feature
    - wear-link(add)
    - other

Would you agree above?

**Comment by takahirom** [comment]
The thing is, I don't currently have a wearable device. Also, I'm the one releasing this app, so I think it is a little too risky.

**Comment by hiroaki404** [comment]
Understood. Then let's quit developing it this time. Thank you for your consideration!
