### ISSUE TITLE
Connecting Compose ProfileCardScreen as an iOS app screen

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2024#814]
Currently, the iOS app only has a native screen for creating a Profile card. However, instead of using this native implementation, we want to integrate the Compose Multiplatform ProfileCardScreen into the iOS app. The goal is to have the Compose editing screen appear when the profile card icon in the bottom navigation bar is tapped in the iOS app.

**Comment by Corvus400** [comment]
I would like to work on this task.🙋‍♂️

**Comment by Corvus400** [comment]
Perhaps it can be done by referring to the contributor screen, so I would like to try it, although it seems difficult.
![Simulator Screenshot - iPhone 15 - 2024-08-27 at 11 03 14](https://github.com/user-attachments/assets/0d5d41f9-6b1a-4ecd-9ec6-30991956149b)

**Comment by takahirom** [comment]
Thanks!
