### ISSUE TITLE
ComposablePreviewScanner Library dependency Issues

### ISSUE THREAD

**Issue by Pluu** [DroidKaigi/conference-app-2024#830]
I find this in the Android Studio environment.

ComposablePreviewScanner 0.1.3 is trying to access the Androidx compose runtime 1.4.8.
However, that version does not exist.

In version 0.2.0, the dependency was resolved to 1.6.6.
The latest version is 0.3.0.
I'm not sure what this library is used for, so I'm hoping someone in the know can help me out.

- 0.1.3 pom : https://jitpack.io/com/github/sergio-sastre/ComposablePreviewScanner/android/0.1.3/android-0.1.3.pom
- 0.2.0 pom : https://jitpack.io/com/github/sergio-sastre/ComposablePreviewScanner/android/0.2.0/android-0.2.0.pom
- AndroidX compose runtime : https://developer.android.com/jetpack/androidx/releases/compose-runtime?hl=en

<img width="1208" alt="a" src="https://github.com/user-attachments/assets/b68b9c3f-1ac6-4c68-a12e-70595431ce50">

**Comment by takahirom** [comment]
If we can update it and it passes CI, I think it is okay to proceed with the update. We can also download the store screenshot artifact to check that the screenshots are saved for previews.

**Comment by Pluu** [comment]
I'll try modifying it based on that library.
