### ISSUE TITLE
Center crop the image when it is not square.

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2024#840]
We are showing an error when the image is not square. Ideally, [we would like to crop the image as we want, but it seems difficult to implement in the given time](https://github.com/DroidKaigi/conference-app-2024/issues/413). Therefore, I think it is better to have a center crop logic.
<img src=https://github.com/user-attachments/assets/8a5ad5f5-1485-4abd-bf30-f0c6612b6859 width=200 />

You can refer to this site to see what center crop is.
https://thoughtbot.com/blog/android-imageview-scaletype-a-visual-guide

**Comment by mannodermaus** [comment]
✋ (will take care of it tonight after work)

**Comment by takahirom** [comment]
Thanks! @mannodermaus
