### ISSUE TITLE
Input values ​​are not maintained on the profile edit screen

### ISSUE THREAD

**Issue by Songgyubin** [DroidKaigi/conference-app-2024#883]
## Issue
When you rotate the screen or move to another tab on the profile edit screen, the entered values ​​are not maintained.

If that was intentional, why not modify it to keep it?
I think it would be better for the user experience to keep it.

If this issue is accepted, I would like to make changes. 🙋‍♂️
## Video
<video src="https://github.com/user-attachments/assets/490aa8c2-1e94-4eff-b783-4334d9d24779" width="300" >

**Comment by takahirom** [comment]
You can do it because the assignee does not exist, but there is an issue with this. 👍
https://github.com/DroidKaigi/conference-app-2024/issues/737
