### ISSUE TITLE
TextLink weight and color are different from Figma

### ISSUE THREAD

**Issue by kosenda** [DroidKaigi/conference-app-2024#884]
## Overview
As the title says, the text link for AboutScreen's AboutDroidKaigiDetailSummaryCard is different from Figma

|Figma|Actual|
|---|---|
|<img src="https://github.com/user-attachments/assets/6f93a79a-6e65-40c6-b8ab-4bbc4259d265" width="300">|<img src="https://github.com/user-attachments/assets/01aa792d-6c6e-4d9d-9fa6-2144381f9eda" width="300">

## Ref
Changing ClickableLinkText would solve the problem.

https://github.com/DroidKaigi/conference-app-2024/blob/53f341822fd0f4a128db83648e805d75156c7f2a/core/designsystem/src/commonMain/kotlin/io/github/droidkaigi/confsched/designsystem/component/ClickableLinkText.kt#L87-L88

## Figma
https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI?node-id=54982-75342&t=5liPuDQkrKozbZoq-4

**Comment by takahirom** [comment]
Thanks!
