### ISSUE TITLE
On devices with a small width, the shared image in the profile card will be something unintended.

### ISSUE THREAD

**Issue by Corvus400** [DroidKaigi/conference-app-2024#890]
- The video that ran on the SmallPhone emulator is as follows.
- As you can see in the video, the cards will be separated if you use portrait mode.
In Landscape mode, it probably looks fine.

SmallPhone Portrait | SmallPhone Landscape
:--: | :--:
<video src="https://github.com/user-attachments/assets/278f6d34-d1b6-49cc-b81e-3babebb0c9aa" width="300" > | <video src="https://github.com/user-attachments/assets/b0aa9a75-31fe-4195-a8ad-e6c9e1084e33" width="300" >

- For now, if you reduce the horizontal padding by 20.dp, the noticeable display distortion will disappear.

https://github.com/DroidKaigi/conference-app-2024/blob/53f341822fd0f4a128db83648e805d75156c7f2a/feature/profilecard/src/commonMain/kotlin/io/github/droidkaigi/confsched/profilecard/component/ShareableCard.kt#L94

- However, since ShareableCardContent is dependent on the width and height of the device, this kind of workaround will not work for devices with a smaller width than SmallPhone.

- It is probably difficult to deal with problems like this without a way to display images of a fixed size (1,200px wide and 630px tall) on any device.

**Comment by Corvus400** [comment]
I've tried it out, and it looks like it might be possible to output a fixed size on any device, so I'll try it myself.

**Comment by mannodermaus** [comment]
Great catch. 👀

Since this composable is not _actually_ displayed on screen, I wonder if we can force it into a more consistent layout by giving it a specific size? In other words, could it work if we assigned `size(1200.dp, 630.dp)` to `ShareableCardContent`'s modifier?

**Comment by Corvus400** [comment]
@mannodermaus 
I'm sorry. 🙇 
I've made a PR, so if you could try outputting it in portrait and landscape on your own device and check for any design issues, that would be very helpful. 🙇

**Comment by mannodermaus** [comment]
No problem, I will check it in a moment! At first glance, your PR looks great and should work, though. Good job!

**Comment by mannodermaus** [comment]
お待たせしました。The layout seems to work pretty well and looks identical, no matter if I export it portrait or landscape – nice. I was able to create a change when changing the font size and display size to the maximum, though. The landscape version looks a bit odd with this and changes its shape. This might be negligible, though.

||Portrait|Landscape|
|---|---|---|
|**Normal font**|<img src="https://github.com/user-attachments/assets/5e11a505-4aea-4ec9-b17c-e5ad1a558256" width="300" />|<img src="https://github.com/user-attachments/assets/f1738df9-1bc0-47dc-8c80-ca5565a622ae" width="300" />|
|**Large font**|<img src="https://github.com/user-attachments/assets/e75074de-fbb3-433b-b401-9517e2f53c79" width="300" />|<img src="https://github.com/user-attachments/assets/31ed79b6-b624-49a8-84e9-a75b5779e8e8" width="300" />|

**Comment by Corvus400** [comment]
@mannodermaus 
If we handle corner cases in the current PR, it will be difficult to review, so I would like to create a new issue and handle it there. 🙇 
I'm sorry. 🙏

**Comment by mannodermaus** [comment]
I agree that keeping it separate is the way to go. Let's get this improvement in first and then we can define the next one. 😊

**Comment by Corvus400** [comment]
@mannodermaus 
Thank you for waiting. 🙇 
We have created a new PR, and have addressed the problem of the display breaking up when the font or display scale is made smaller or larger. 🙏
