### ISSUE TITLE
In EditScreen, the style of select_theme is different from Figma

### ISSUE THREAD

**Issue by kosenda** [DroidKaigi/conference-app-2024#898]
## Overview
As the title says, but the style seems to be different from Figma

| - |image|
|---|---|
|Figma|<img src="https://github.com/user-attachments/assets/df4e9149-02d1-4632-84c0-6079d0081344" width="350">|
|Actual|<img src="https://github.com/user-attachments/assets/6a277b98-b36b-4baf-a35d-7f87dde2f142" width="350">|

**Comment by hiwa0** [comment]
Can I work on this task?
