### ISSUE TITLE
TimeTableGridItem title text line count is different from Figma

### ISSUE THREAD

**Issue by s-kamada** [DroidKaigi/conference-app-2024#902]
## Overview

As far as Figma is concerned, it should ellipsis if the number of rows in the Title of a TimeTableGridItem is more than 3, but that does not seem to be the case in practice.

After a brief investigation, it seems that it cannot be fixed by simply modifying [the maxLines of the corresponding Text Composable](https://github.com/DroidKaigi/conference-app-2024/blob/7b153b56db624975ba19b599a52a373e4b16d255/feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/component/TimetableGridItem.kt#L253-L257), and that it may be necessary to adjust [the function that calculates the height of the text](https://github.com/DroidKaigi/conference-app-2024/blob/633113d4f490cc760bbe1ee962084167255ce662/feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/component/TimetableGridItem.kt#L333) or [the weight of the Column](https://github.com/DroidKaigi/conference-app-2024/blob/633113d4f490cc760bbe1ee962084167255ce662/feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/component/TimetableGridItem.kt#L154-L185).

|Figma|Actual|
|:--:|:--:|
|![スクリーンショット 2024-08-31 18 15 53](https://github.com/user-attachments/assets/4079ad67-a608-41a4-bae9-b20c4098153f)|<img width=300 src="https://github.com/user-attachments/assets/a88e4701-750b-4d0f-a52f-7e31390f7a23"/>|

**Comment by Matuyuhi** [comment]
@takahirom 
May I try this issue?

**Comment by takahirom** [comment]
Thanks! This issue might be a little difficult. Please let me know if you want to give up. Assigned 👍

**Comment by Matuyuhi** [comment]
I fixed this [PR](https://github.com/DroidKaigi/conference-app-2024/pull/917)!
I responded by changing from Column() to a custom layout using Layout().
