### ISSUE TITLE
Display the total number of persons in ContributorsScreen

### ISSUE THREAD

**Issue by kosenda** [DroidKaigi/conference-app-2024#903]
## Overview
Many people are involved in DroidKaigi, and I thought it would be easier to convey the atmosphere of more people being involved if the number of staff and contributors were listed.

## Sample

https://github.com/user-attachments/assets/2ce8487e-3d2f-451d-afb4-c360c2d83d21

```kotlin
val animatedCount by animateIntAsState(
    targetValue = uiState.staff.size,
    animationSpec = tween(
        delayMillis = 300,
        durationMillis = 1000,
        easing = EaseOutQuart
    )
)
```

**Comment by kosenda** [comment]
@nobonobopurin @takahirom 
It may be an unnecessary feature, but what do you think?

**Comment by nobonobopurin** [comment]
@kosenda 
I think it's really great🤩👍

**Comment by takahirom** [comment]
Regarding the staff, we do not display every staff member on the staff screen, so the number may be inaccurate. Therefore, could we only implement this on the Contributor screen?

**Comment by kosenda** [comment]
I see...！

@nobonobopurin 
I would like to see this reflected in the design of ContributorsScreen 🙇

**Comment by nobonobopurin** [comment]
@kosenda cc @takahirom 
I have reflected this in the design of the ContributorsScreen. Please have a look! 🙇‍♂️
[Figma](https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI?node-id=54985-76132&t=IaCt19D95CQpZouo-4)
![contributor](https://github.com/user-attachments/assets/c648b8d9-61d4-4590-9ec6-faa99766cb6a)

**Comment by raseln** [comment]
✋

**Comment by takahirom** [comment]
Thanks! Assigned 👍
