### ISSUE TITLE
[iOS・Compose Multiplatform] Bottom tab bar is covering create card button

### ISSUE THREAD

**Issue by woxtu** [DroidKaigi/conference-app-2024#905]
# Overview

On the iOS app, the bottom tab bar is covering the create card button on the profile card screen.

# Screenshot

<img src="https://github.com/user-attachments/assets/96354b3b-9043-4432-8d3f-542b25cd1408" width=300>

**Comment by takahirom** [comment]
Maybe it is a Compose Multiplatform's screen.

**Comment by Corvus400** [comment]
After doing a little research, it seems that the only immediate fix is to set the contentPadding bottom to 30dp.
I think the real thing is to get the inset from the iOS side, convert it to dp, and set it as padding, but from what I've looked into, it seems like various modifications will be necessary.
(And there is no guarantee that it can be fixed for sure at the moment.)

https://github.com/DroidKaigi/conference-app-2024/blob/38c9bcef1598b28246568d0a7fed3980da93eee1/feature/profilecard/src/iosMain/kotlin/io/github/droidkaigi/confsched/profilecard/ProfileCardViewController.kt#L18-L26

For now, I plan to release a workaround PR. 🏃
