### ISSUE TITLE
In TimetableScreen, SpearkerIcon blinks when offline and scrolling

### ISSUE THREAD

**Issue by kosenda** [DroidKaigi/conference-app-2024#912]
## Overview
It is easier to see in the video, but the speakerIcon blinks when it is loading, offline, and scrolling.

https://github.com/user-attachments/assets/323d6ad3-2617-45df-88c4-3fe416efd5a2

**Comment by Corvus400** [comment]
I want to start working on this task.🙋‍♂️

**Comment by takahirom** [comment]
@Corvus400 Thanks!
