### ISSUE TITLE
In TimetableList, Items cannot be displayed at the bottom of the screen by the offset of DayTab

### ISSUE THREAD

**Issue by kosenda** [DroidKaigi/conference-app-2024#914]
## Overview
As the title says, the DayTab offset moves when scrolling, making it impossible to display the contents of the list at the bottom.

https://github.com/user-attachments/assets/1acdb398-aeae-4f0b-99ff-3ceb69a838b8

**Comment by takahirom** [comment]
I haven't noticed. Thanks.
![image](https://github.com/user-attachments/assets/84ba191b-09fa-4805-a0b3-18c705bb0f7f)

**Comment by kktaro** [comment]
🙋‍♂️

**Comment by takahirom** [comment]
Thanks! Assigned 👍

**Comment by Corvus400** [comment]
Would you like to reopen this issue?👀
