### ISSUE TITLE
Illegal version namber in about screen.

### ISSUE THREAD

**Issue by CookieySun** [DroidKaigi/conference-app-2024#918]
https://x.com/CookieySun/status/1830242105039733246?t=kM3phmvnfMJ8brUs0ZR0OQ&s=19

**Comment by takahirom** [comment]
I'm not sure but it might be a cache problem. 👀

**Comment by CookieySun** [comment]
I have tried deleting the storage, but it is still at 1.0.1.
https://github.com/user-attachments/assets/02b1933b-f720-450d-b0e8-f8e260cf5a95

**Comment by takahirom** [comment]
Sorry, I mean it is my build environment cache.

**Comment by takahirom** [comment]
I think this is solved by 1.2.0. Thank you for reporting.
