### ISSUE TITLE
In EditScreen, it would be better to take the focus off the text field once the keyboard is hidden

### ISSUE THREAD

**Issue by kosenda** [DroidKaigi/conference-app-2024#920]
## Overview
- I personally find it little strange that the keyboard is not displayed but continues to get focus. I thought it might be better to remove the focus when the keyboard is hidden, or to make it possible to remove the focus by tapping outside the text field.

https://github.com/user-attachments/assets/071dbbd0-27ce-4d50-8561-c972aa7452ae

**Comment by Corvus400** [comment]
I want to work on this problem.
