### ISSUE TITLE
TimetableItemTag color is different from Figma

### ISSUE THREAD

**Issue by kosenda** [DroidKaigi/conference-app-2024#930]
## Overview
It is very confusing, but the color of TimetableItemTag is often different from Figma.

|Figma|Actual|
|---|---|
|<img src="https://github.com/user-attachments/assets/f0079298-269c-421a-844c-3e3d93a9ab81" width="300">|<img src="https://github.com/user-attachments/assets/adc4fcee-6533-4c72-aaf6-f493d2167fcb" width="300">|

## Detail
- If you look carefully at [Figma](https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI?node-id=54888-45493&t=s8UJNDtl4U7UDoV5-4) , you will notice that the colors of the tag text icons, and outlines are different

<img width="582" alt="image" src="https://github.com/user-attachments/assets/17620833-8cd0-4a1e-a665-4359ccb101f1">

## Cause
As shown below, the color of the Tag could only be specified as one color, so it was always different from Figma.

https://github.com/DroidKaigi/conference-app-2024/blob/cc27b71baf6e3701ee7d5a30f41d95ac2dd70c94/core/droidkaigiui/src/commonMain/kotlin/io/github/droidkaigi/confsched/droidkaigiui/component/TimetableItemTag.kt#L22-L28

## Revision Method (Draft)
I think it would be a good idea to allow multiple colors to be passed with a single argument, like ButtonColors in Material.

**Comment by mannodermaus** [comment]
✋

**Comment by takahirom** [comment]
Thanks! Assigned 👍

**Comment by mannodermaus** [comment]
I reached out to @nobonobopurin [on Figma](https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC?node-id=54888-45066#933928094) to inquire about this. In my personal opinion, the text color and outline color should be the same, but let's see what they say. 🙇‍♂️ 

<img width="750" alt="Screenshot 2024-09-04 at 19 52 21" src="https://github.com/user-attachments/assets/912a86a9-6119-4f1f-9d5c-2c7a3f803919">

**Comment by nobonobopurin** [comment]
@mannodermaus Thanks for waiting! I replied on Figma. I set the outline color differently on purpose, but I’m fine with changing it to be the same. Let me know if you want to change it, and I'll update it on Figma.

**Comment by mannodermaus** [comment]
Okay, thank you for confirming! I will change the outline color then, no problem at all. Just wanted to make sure. 🙇‍♂️
