### ISSUE TITLE
In SearchScreen, TimetableItemTag content differs from Figma

### ISSUE THREAD

**Issue by kosenda** [DroidKaigi/conference-app-2024#931]
## Overview
In SearchScreen, the TimetableItemTag should be a date, but the language is displayed.

|Figma|Actual|
|---|---|
|<img src="https://github.com/user-attachments/assets/7328b6db-1bf6-4a88-87a2-9b3270e54e0a" width="300">|<img src="https://github.com/user-attachments/assets/3be64d30-8d46-414a-9a5d-5f85c0cf55fe" width="300">|

## Figma
https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI?node-id=54965-73763&t=s8UJNDtl4U7UDoV5-4

**Comment by mannodermaus** [comment]
✋

**Comment by takahirom** [comment]
Thanks! Assigned 👍
