### ISSUE TITLE
Replace Compiler Options instead of deprecated Kotlin Options.

### ISSUE THREAD

**Issue by hiroaki404** [DroidKaigi/conference-app-2024#933]
It is not required, but there is a lint warning. We would prefer to use Compiler Options instead of deprecated Kotlin Options. In the build-logic.

It needs to work with Android and iOS builds, tests, detectKt, etc. Is there anything else we need to check?

Maybe we should refrain from doing this now because we may have build problems.

**Comment by Aniokrait** [comment]
I will try this.
I think it is Ok if `gradlew build` and `make bootstrap` work as is.
