### ISSUE TITLE
Delete method classes that were used last year but not this year.

### ISSUE THREAD

**Issue by Corvus400** [DroidKaigi/conference-app-2024#938]
## Overview

There seem to be various processes that we used to use until last year, but that we haven't used at all this year due to changes in the architecture.
I think it's too early to delete them now, but it might be a good idea to start working on deleting them next week, when the event is being held.

## Example

https://github.com/DroidKaigi/conference-app-2024/blob/main/core/droidkaigiui/src/commonMain/kotlin/io/github/droidkaigi/confsched/droidkaigiui/UiStateBuilder.kt

**Comment by takahirom** [comment]
Sounds good 👍

**Comment by natura1ie** [comment]
May I give it a try?
