### ISSUE TITLE
[iOS・Compose Multiplatform] Navigation on about isn't working as expected

### ISSUE THREAD

**Issue by woxtu** [DroidKaigi/conference-app-2024#953]
# Overview

Tapping the back button on the about screen implemented by Compose Multiplatform takes us to an unexpected screen.

# Steps to reproduce

1. Open the about screen
2. Tap the "Switch Compose Multiplatform" button and switch UI
3. Tap the contributor button and open the contributor screen
4. Tap the back button

# Video

<video src="https://github.com/user-attachments/assets/38a57b0d-4b90-419b-b88a-a3c33ef1dc16" width="300" >

**Comment by Corvus400** [comment]
This is a known issue that is already being discussed here.
https://github.com/DroidKaigi/conference-app-2024/discussions/882
