### ISSUE TITLE
IosComposeKaigiTest fails

### ISSUE THREAD

**Issue by Aniokrait** [DroidKaigi/conference-app-2024#964]
# Overview
As the title says, IosComposeKaigiTest fails when running `./gradlew build`.

```
> Task :app-ios-shared:compileTestKotlinIosArm64 FAILED
e: file:///Users/tak/Documents/develop/droidkaigi/2024/conference-app-2024/app-ios-shared/src/iosTest/kotlin/io/github/droidkaigi/confsched/shared/IosComposeKaigiTest.kt:62:25 No value passed for parameter 'snackbarHostState'.
e: file:///Users/tak/Documents/develop/droidkaigi/2024/conference-app-2024/app-ios-shared/src/iosTest/kotlin/io/github/droidkaigi/confsched/shared/IosComposeKaigiTest.kt:62:25 No value passed for parameter 'onLicenseScreenRequest'.
```

You can reproduce it by running `./gradlew :app-ios-shared:compileTestKotlinIosArm64`.
(I don't know how to run single iOS test on Android Studio🤔.)

**Comment by Corvus400** [comment]
I'm sorry, I made the same mistake before and fixed it, but I've missed fixing it again... :disappointed: 
I'll deal with it now. :runner: 
https://github.com/DroidKaigi/conference-app-2024/pull/881

**Comment by Aniokrait** [comment]
@Corvus400 
I appreciate you fixing it, but I'm sorry, it still fails.
Some more fixing would be needed.
<img width="1502" alt="スクリーンショット 2024-09-06 22 51 28" src="https://github.com/user-attachments/assets/83a8ad87-9ba6-4389-a062-88db0f807c27">

@takahirom 
Can you reopen the issue? Or should I create another one?
