### ISSUE TITLE
Canceled special session's message is not showed

### ISSUE THREAD

**Issue by Aniokrait** [DroidKaigi/conference-app-2024#987]
# Overview
Accoridng to the official web site, the session "Androidの未来をつくる： 多様性のあるチームの力" has been canceled.
However, the session doesn't show any messages on Android app.
Currently, only normal session shows a message but special session doesn't.  

related issue #217

# Image
|[official web site](https://2024.droidkaigi.jp/timetable/9-12/)|Android app|
|-|-|
|<img width="626" alt="スクリーンショット 2024-09-06 23 06 01" src="https://github.com/user-attachments/assets/3d3f9b9b-b8c1-4079-9a12-68384cb9aa09">|<img width="300" src="https://github.com/user-attachments/assets/1cdd7ecd-14a2-4960-949c-8c807c706c2e" />|

**Comment by Aniokrait** [comment]
I'll handle this.

**Comment by takahirom** [comment]
@Aniokrait Thanks! 🙏
