### ISSUE TITLE
Use implement(xxx) for foundation:1.8.0-alpha01 instead of resolutionStrategy

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2024#995]
Now that we are specifying a bigger version, I think we can remove this, and we can normally depend on foundation:1.8.0-alpha01 like `implementation(libs.composeFoundation)`.

https://github.com/DroidKaigi/conference-app-2024/pull/984/files#diff-c0dfa6bc7a8685217f70a860145fbdf416d449eaff052fa28352c5cec1a98c06R28-R30

**Comment by bobUmi** [comment]
I'd like to try this issue 🙋

**Comment by yt8492** [comment]
I would like to work on this task.
