### ISSUE TITLE
Extract KaigiAppCompositionLocalProvider into regular methods.

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2024#996]
I think ProvideAndroidContextToComposeResource is not providing a value to CompositionLocal, and I would not like the method name to be misleading.
https://github.com/DroidKaigi/conference-app-2024/pull/984/files#diff-7d5fc717625e9525dcc1ddbdffa972383805fda85cc2d70c5a70239a7c0cc567R93

It will be something like this

```kotlin
CompositionLocalProvider(LocalClock provides clockProvider.clock()) {
          if (isTest()) {
            ProvideAndroidContextToComposeResource()
        }
        repositoryProvider.Provide {
            KaigiApp(
                windowSize = windowSize,
                fontFamily = fontFamily,
                displayFeatures = displayFeatures,
            )
        }
}
```

**Comment by sanao1006** [comment]
✋

**Comment by takahirom** [comment]
Thanks! Assigned 👍
